### ISSUE TITLE
face_recognition_model.bin

### ISSUE THREAD

**Issue by perfixel** [vladmandic/face-api#101]
### Discussed in https://github.com/vladmandic/face-api/discussions/100

<div type='discussions-op-text'>

<sup>Originally posted by **perfixel** April  8, 2022</sup>
Hello, I've come across a problem where "sometimes" my browser "chrome" fails to load the "face_recognition_model.bin" file giving me the "net::ERR_BLOCKED_BY_CLIENT" error for that file. I noticed that it's a 6 MB+ file.
In my project I only use the face detection method. I don't use anything else but detecting the faces .. is there a way to minimize this file size or the whole package to suit only my needs? like only detecting faces. no expressions or age or etc
![download (8)](https://user-images.githubusercontent.com/33189075/162345489-38af6768-6069-4108-b6e1-ca28cfa6c60e.png)
?</div>

**Comment by vladmandic** [comment]
`net::ERR_BLOCKED_BY_CLIENT` error is almost always issue with your browser - do you have some extension installed that is misbehaving? for example, ad-blocker.

anyhow, `face-api` only loads models YOU specified - **it does not load everything by default**.  
you're asking how to load only detection, but check your code - you are yourself loading different models that you say you don't need.
