### ISSUE TITLE
Low accuracy with TinyFaceDetector

### ISSUE THREAD

**Issue by anuragsingh228** [vladmandic/face-api#103]
Hey, thanks for the library.

I have two use cases:-
1. Detect Landmarks of images (we call it baseImage)
2. Match a certain set of images with the image that we received in step 1.

I was using the old face-api. 
For the first use case,
`const detectionsWithLandmarks = await faceapi
      .detectAllFaces(canvas, getFaceDetectorOptions(TINY_FACE_DETECTOR))
      .withFaceLandmarks(true);
`
I was using the TinyFaceDetector(threshold: 0.5), but the accuracy was low. So I tried SSDMobileNet(min-confidence: 0.4).

I ran a script of 5000 images with both models.
TinyFaceDetector: {recognized: 4971, not-recognized: 28}
SSDMobileNet: {recognized: 4791, not-recognized: 208}
Not recognized increeased to about 10x.
I read that SSDMobileNet is supposed to perform better. Am I doing something wrong here?

For the second use case, I find out the descriptor in the base Image and the currentImage and find the euclidian distance between the two. Is this alright or the faceMatcher method will provide better results?

In this [issue](https://github.com/justadudewhohacks/face-api.js/issues/821#issuecomment-925754787) you mentioned finding the descriptor of the face than the whole image. Can you please help me understand this? 

Also, if you can suggest anything for my use cases to get the best from this library, it would be really helpful of you. 
Thanks.

**Comment by vladmandic** [comment]
> Is it only because you want to reduce dependency on another library, or something else?

Primarily for troubleshooting purposes as ppl report they get unexpected outputs, but I don't even know what the input is if they're using some unknown 3rd party tool to parse image to start with  

Once code is working, users can any library

**Comment by vladmandic** [comment]
unrelated, if you're looking to compare large number of face descriptors in bulk, you may want to take a look at my experiments with multithreaded compare function and/or wasm native implementation: <https://github.com/vladmandic/human-match>

**Comment by anuragsingh228** [comment]
Absolutely, will take a look. Thank you again for your time.
