### ISSUE TITLE
CPU-only build

### ISSUE THREAD

**Issue by jhfoo** [vladmandic/face-api#111]
**Issue Description**
tfjs not supported for FreeBSD. 

**Steps to Reproduce**
Try to install @tensorflow/tfjs. It will failed with unsupported OS.

**Expected Behavior**
Install passes.

**Environment
FreeBSD v13.1.

- Module version?
Latest

- Built-in demo or custom code?
NA

- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
NA

- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)?
Nodejs v16

- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)?
FreeBSD

- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?
NA

**Additional**
Do you plan a build for CPU-only (slow performance, but better than nothing), or recommend to use original repo code?

**Comment by vladmandic** [comment]
First things first, I have no idea what to expect on FreeBSD as it was never tested on it. But having said that...

a) If you're ok using ESM format (instead od CJS which which normally used in NodeJS) you can use `face-api` as cpu only in nodejs environments right now, you just have to manually specify `dist/face-api.esm.js` as import. Although no clue if this would actually work on FreeBSD

b) Alternatively, you can clone this repo and create a CJS build of CPU-only for NodeJS - its pretty trivial. I can share the steps (just edit `build.json` to add one more target and run `npm run build`), just don't plan to release it as there is no demand for it. But you still need to get `@tensorflow/tfjs-core`, `data`, `layers` & `backend-cpu` to install.

c) Even better alternative would be to use that, but augment it with `@tensorflow/tfjs-backend-wasm` - which you also have to build yourself for FreeBSD, but it would be 3-5x faster than CPU only for sure. again, this is pretty easy I have build scripts ready in my fork of TFJS: <https://github.com/vladmandic/tfjs>

**Comment by vladmandic** [comment]
Any updates?

**Comment by jhfoo** [comment]
I apologize for my slow response. My server disks got flaky and I'm rebuilding my development framework. Will get back to you quickly what I was able to do.

**Comment by jhfoo** [comment]
> c) Even better alternative would be to use that, but augment it with @tensorflow/tfjs-backend-wasm - which you also have to build yourself for FreeBSD, but it would be 3-5x faster than CPU only for sure. again, this is pretty easy I have build scripts ready in my fork of TFJS: https://github.com/vladmandic/tfjs

Will try this option and let you know how that went!

**Comment by jhfoo** [comment]
This is the error message received trying to run the wasm build script:
```
app@dev-penn ~/tfjs %./scripts/build-wasm.sh                               1:08
Found bazel 5.1.0
Found Python 3.8.13
Cleaning Bazel build cache
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
Extracting Bazel installation...
ERROR: The 'clean' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/main/build-ref.html#workspace
```

Using:
- bazel 5.1.0
- python 3.8.13

**Comment by vladmandic** [comment]
Run full `npm build`, it runs build-wasm as part of a step.

**Comment by jhfoo** [comment]
Not sure if it's FBSD related: bumped into an issue with ```npm run build```

```
app@dev-penn ~/tfjs %npm run build                                        11:47

> @vladmandic/tfjs@3.18.0-20220602 build
> npm run download && npm run patch && npm run build-wasm && npm run build-tfjs


> @vladmandic/tfjs@3.18.0-20220602 download
> scripts/download.sh

Updating TFJS sources to latest version
Saved working directory and index state WIP on master: b72b202 Bump protobufjs in /e2e/benchmarks/browserstack-benchmark (#6491)
Already up to date.

> @vladmandic/tfjs@3.18.0-20220602 patch
> scripts/prepare.sh

Detected version: 3.18.0-20220605
Creating op list imports
sed: 1: "1i export const json = ": command i expects \ followed by text
```

**Comment by vladmandic** [comment]
yeah, that seems to be due to `sed` on **fbsd** acting differently than on **linux** - its supposed to run a simple string replace, no idea why **fbsd** doesn't like it. feel free to play with the script, its pretty much the last line in `scripts/prepare.sh`

**Comment by vladmandic** [comment]
closing the issue as cpu-only build will not be part of distribution, but i will assist if a user wishes to produce one.
