### ISSUE TITLE
Can't use WASM backend

### ISSUE THREAD

**Issue by ScottDellinger** [vladmandic/face-api#118]
**Issue Description**
When attempting to load the WASM backend, I'm receiving the following error:

Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="a" error: module is not an object or function

**Steps to Reproduce**
face-api is being loaded by adding a script tag to the page dynamically. Software is loaded on top of a variety of different sites. Unfortunately, we're encountering some users whose devices do not support WebGL (or they have hardware acceleration disabled in Chrome for some reason) and we'd like to use the WASM back end instead.

`<script src="https://d2hj51f62xpwi7.cloudfront.net/v2/dev/scripts/face-api.js" id="faceapi"></script>`

`const usePlatformFetch = true;
faceapi.tf.setWasmPaths('https://integrity-ui.s3.ca-central-1.amazonaws.com/v2' + urlPathMode + '/scripts/faceapidist/', usePlatformFetch);
faceapi.tf.setBackend('wasm');`

**Expected Behavior**
tfjs should use WASM back end.

**Environment
In browser.

- Module version? Latest version of face-api being used
- Built-in demo or custom code? Custom code
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? js
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Chrome 104
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Windows 11
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)? None

**Comment by vladmandic** [comment]
i have no idea what is:
> 'https://integrity-ui.s3.ca-central-1.amazonaws.com/v2' + urlPathMode + '/scripts/faceapidist/'`

but i just tried from a common cdn and no issues:

```js
  await faceapi.tf.setWasmPaths(`https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@${faceapi.tf.version_core}/dist/`);
  await faceapi.tf.setBackend('wasm');
```

btw, 

> module is not an object or function

typically this means either corrupt wasm binary (can happen if server replies with wrong content-type) or version mismatch (wasm binary must match version of tfjs used, that's why i'm using dynamic version in the example above).

**Comment by ScottDellinger** [comment]
@vladmandic Fantastic... that fixed the issue. Thanks for the incredibly fast response! Closing this ticket.
