### ISSUE TITLE
Unable to Create dist with @vladmandic/face-api

### ISSUE THREAD

**Issue by VedantMadane** [vladmandic/face-api#119]
**Issue Description**
Tried `npm run build` after having @vladmandic/face-api as dependency. Also tried using yarn to build. In both cases, building failed.

/  Building for production...

 ERROR  Failed to compile with 1 error                      11:25:40 am

 error  

No bundles were parsed. Analyzer will show only original module sizes from stats 
file.

Webpack Bundle Analyzer saved report to C:\Users\VedantM\recruitlive\recruitment-applicant-client\dist\report.html
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.1 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\VedantM\AppData\Roaming\npm-cache\_logs\2022-08-25T05_55_41_199Z-debug.log

**Steps to Reproduce**

**Expected Behavior**

**Environment

- Module version?
- Built-in demo or custom code? Built-in demo
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? vue
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)?
- npm version 6.14.15
- node version v14.18.1
-     "vue-cli-plugin-webpack-bundle-analyzer": "^1.4.0"
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)?
- Windows 10
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)? webpack. Same issue when using vite

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
I'll take a look next week as I'm currently traveling.


Most commonly this is related to webpack getting confused should it use node or browser version - try importing exact one instead (e.g. @vladmandic/face-api/dist/face-api.esm.js)

**Comment by VedantMadane** [comment]
Happy journey and travel safe🏁

**Comment by vladmandic** [comment]
i'm taking a look and yes, it does sound like `vue-cli-service` which provides dev server and hot-module-reload is creating ugly internal `webpack` configuration so it totally gets it wrong if it should use nodejs or browser module.  

now, i have never used `vue` but its a very similar problem to when using `nextjs` and solution there is to use dynamic imports.
take a look at <https://github.com/vladmandic/human-next> on how the basic project using next would look like  
and especially dynamic import <https://github.com/vladmandic/human-next/blob/6f6b9ee8f23f02a5753b20e7d8249c0d75334495/components/RunHuman.tsx#L30>

this is pretty much all i can say as i'm really not a `vue` user.

**Comment by vladmandic** [comment]
any updates?

**Comment by VedantMadane** [comment]
For the time being I'm using @mediapipe/face_recognition but I want to thank you for creating faceAPI and human and open-sourcing them. I've a lot to learn before getting to the bottom of solving this.
