### ISSUE TITLE
Face-API: import this lib cause critical dependency warning

### ISSUE THREAD

**Issue by ljnferreira** [vladmandic/face-api#132]
## Issue Description
import { detectSingleFace, fetchImage, nets, TinyFaceDetectorOptions }  from '@vladmandic/face-api/' emits WARNING in ./node_modules/@vladmandic/face-api/dist/face-api.esm.js 8:47-54
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

The same happens with all alternative imports

### Steps to Reproduce
Install and use lib in a CRA environment with react-scripts v 5.0.1 (webpack 5)
returns error on console

### Environment

Face-API library version? 1.7.6
Built-in demo or custom code? custom
Type of module used (e.g. js, esm, esm-nobundle)? esm
Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Node 16.14 / Chrome 107
OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Manjaro 
Framework (if any) (e.g. React, NextJS, etc.)? React

**Comment by ljnferreira** [comment]
![image](https://user-images.githubusercontent.com/9002838/201435990-fa9cfb72-c033-472f-8b5e-b68b239ee028.png)

**Comment by vladmandic** [comment]
I just wrote a post on that - see #134 for details.  
I'm closing the issue as resolved, but feel free to post on this thread with any further questions.
