### ISSUE TITLE
TypeError: H(...).platform.isTypedArray is not a function

### ISSUE THREAD

**Issue by 0xori** [vladmandic/face-api#153]
im getting this error when trying to load models
```
 await  #faceapi.nets.ssdMobilenetv1.loadFromUri("/models")
```
happens when using  @tensorflow/tfjs - ^4.2.0
might be relatet to this: #https://github.com/tensorflow/tfjs/issues/7273
tried to downgrade to @tensorflow/tfjs 3.7.0 as mentioned in the tfjs issue didn't help

**Comment by vladmandic** [comment]
i have nothing to go on - please fill the issue template!

**Comment by 0xori** [comment]
i was trying to load an automl model using `await automl.loadImageClassification`
the tfjs version was not matching the lib tfjs version. once i downgraded it solved.
