### ISSUE TITLE
Can't detect face on picture

### ISSUE THREAD

**Issue by Reg93** [vladmandic/face-api#155]
Hello, Mr. Mandic! Thank you for your work! I faced with problem that face-api cannot find the face in the picture. How i can improve code or maybe you have solutions for such situations?

If i cut photo face-api finds face but clients can send such big pics, so i need to have solution for such situations

Sorry for grey additions on pic, that is for security.

Real full pic

![photo_2023-02-23_10-20-08](https://user-images.githubusercontent.com/94961770/220919530-045bde32-9a23-4c83-9326-9ee3515577fe.jpg)

**Comment by vladmandic** [comment]
i'm guessing that pattern printed over the photo on the id is causing ml model not to detect face - in which case, not much i can do about it. i've tried with government id issued by a different country and results are better, but still far from perfect.
i'm affraid this just isn't a good use-case for `face-api`.

not sure how much better would it work, but you can try my much newer project: <https://github.com/vladmandic/human>

**Comment by Reg93** [comment]
> i'm guessing that pattern printed over the photo on the id is causing ml model not to detect face - in which case, not much i can do about it. i've tried with government id issued by a different country and results are better, but still far from perfect. i'm affraid this just isn't a good use-case for `face-api`.
> 
> not sure how much better would it work, but you can try my much newer project: https://github.com/vladmandic/human

Ok, thank you for answer! I will try Human project
