### ISSUE TITLE
Slowlinees loading models

### ISSUE THREAD

**Issue by nazzour** [vladmandic/face-api#156]
**Issue Description**
First of all, thank you for your great work. I made some tests on mobile phones and it works well. The only problem is that it takes time to load the models when we first launch the web page. IT takes about 10 seconds. 
**Steps to Reproduce**
npm run dev
open the web page on mobile phone
**Expected Behavior**
Loading could be faster maybe
**Environment
ubuntu for server and iphone 11 for client

**Additional**
I dont know if it is possible but maybe there is a way to load the models faster. I tested both webgl and wasm backends.
Thank you

**Comment by vladmandic** [comment]
loading is already heavily optimized and without specific issue, not much i can do.
i'm closing the issue for now - if there is anything specific that should be looked at, i can reopen it.
