### ISSUE TITLE
Demo Launch Issue

### ISSUE THREAD

**Issue by NolanCassidy** [vladmandic/face-api#160]
**Issue Description**
I have tried node 16 and node 18 on windows 10 and ubuntu 22 and I am getting the error Cannot find module '@vladmandic/pilogger'

I am just trying to run the webcam.html demo on @vladmandic/face-api

**Steps to Reproduce**
git clone
npm i
npm run dev

**Expected Behavior**
see wbcam.html on localhost link

**Comment by vladmandic** [comment]
to run `npm run dev`, you need dev dependencies (and `@vladmandic/pilogger` is part of that).

dev dependencies are NOT installed by default to allow for minimal installation - if users just want to use the library in their own apps, you simply don't need them. 

but to run a web server locally and build code on the fly (which is part of what `npm run dev` does), you do need them.

and to install dev dependencies, simply run `npm install --production=false`
