### ISSUE TITLE
Pitch is not good when Yaw is <-150º or >150º

### ISSUE THREAD

**Issue by cursan-a** [vladmandic/face-api#163]
**Issue Description**

I just noticed that the pitch seems not good when Yaw is <-150º or >150º. Pitch go directly from -15º to 15º (without passing through valeur [14,-14]) even if I try to move really slow my visage

**Steps to Reproduce**

Just try it on [the demo](https://vladmandic.github.io/face-api/demo/webcam.html), place you face on the side (yaw  <-150º or >150º). Move you face slowly up and down and look at the pitch value.

**Expected Behavior**

Having pitch going slowly from -15º to 15º.

**Comment by vladmandic** [comment]
i cannot reproduce as `pitch` angles i'm seeing change linearly and as expected even with extreme `yaw` values.  
btw, do note analyzing extreme angles is not reliable to start with since most of face is obscured.
