### ISSUE TITLE
System requirements

### ISSUE THREAD

**Issue by CropWatchDevelopment** [vladmandic/face-api#178]
Let me start by saying this project is amazing. I can get this to run at 10 or 11 fps on my desktop, 2 on my laptop, i am wondering if this could be run on something like a raspberry pi or jetson nano?
Before i look into getting the hardware, i hope someone has tried it before!

**Comment by vladmandic** [comment]
does it work on rpi with 4gb? yes, but veeery slowly. i cannot say how slow exactly.
jetson nano is really optimized for different types of models, so you wouldn't actually be using its acceleration at all.
