### ISSUE TITLE
Help understanding - bundled version of tfjs

### ISSUE THREAD

**Issue by meeki007** [vladmandic/face-api#18]
I'm trying to allow users to select to use your bundled version of tfjs - OR - select the non-bundled version

Issue I'm having with your bundled version (brain broken):
I set the backend
```JS
faceapi.tf.setBackend('tensorflow');
```
I get an error: Backend name 'tensorflow' not found in registry"

I figure this is because I'm not using
```JS
ts = require(@tensorflow/tfjs-node);
```
as im using your bundled version of tfjs

However if I use a version check without.  ts = require(@tensorflow/tfjs-node) because im using your bundled version
```JS
let faceapi_tf_version_core = faceapi.tf.version_core;
```
I get: 2.7.0

and if I just try to get the Backend without setting it:
```JS
let tf_req = faceapi.tf.getBackend();
```
its undefined.

SO............. how do I check that  your bundled version of tfjs is initialized

Section of code I'm using for this check:

```JS
//lode modules based on switch statment, without break it will load based on first match down.
    switch (nobundle_tensorflow)
    {
      case true:
      let fs = require(tfjs_module_require_value);
      default:
      let faceapi = require(vladmandic_face_api_require_value); //JavaScript face recognition API for nodejs see https://www.npmjs.com/package/@vladmandic/face-api

      // function to initialize tfjs and env settings
      async function init_tfjs()
      {
          await faceapi.tf.setBackend('tensorflow');
          await faceapi.tf.enableProdMode();
          await faceapi.tf.ENV.set('DEBUG', false);
          await faceapi.tf.ready();
      }

      let faceapi_tf_version_core = faceapi.tf.version_core;
      let tf_req = faceapi.tf.getBackend();

      //error check of await function init_tfjs
      var init_tfjs_no_error = true;
      init_tfjs().catch(error => {
      init_tfjs_no_error = ("Could not initialize tfjs " + error);
      });
```

**Comment by vladmandic** [comment]
That's a packaging bug, I'll fix it ASAP.

`tfjs-node` cannot be bundled since it has dependency on `tensorflow.so` (or `tensorflow.dll` on Windows) that is downloaded during `tfjs-node` installation.

So what you see is that JS part of `tfjs-node` is bundled, but it cannot work since it's missing actual tensorflow library.
I'll remove bundled option for NodeJS.

There are no such issues with browser version as CPU and WebGL backends do not require binary packages and WASM backend allows for user-defined binary download.

**Comment by meeki007** [comment]
Whew. I read/learned allot over the last 2 weeks. I hate to use you as unpaid tech support. I feel much better knowing that it was a bug that lead me down a dead end before I cried for help : )

So I verify I understand correctly:
```JS
const faceapi = require('@vladmandic/face-api/dist/face-api.node.js');
```
is not supported as a bundled version as of now.

Make users install: (in my use case)
```JS
tfjs_module_require_value = '@tensorflow/tfjs-node';
```
or
```JS
tfjs_module_require_value = '@tensorflow/tfjs-node-gpu';
```

thanks m8..  happy I found a bug.  Thanks for working with us nodeJS odd balls

**Comment by vladmandic** [comment]
Yup, that's about it.  
I'll modify docs to reflect that as well.

But while I'm at it, I'll redesign the build process like I've already done for some my other projects as  I hate long command lines inside `package.json`

**Comment by meeki007** [comment]
I'm excited to see the changes.

I'm pondering just making a web based version; can be done in node-red. However the idea behind node-red is to use a device, most the time a SBC (single board computer), to do all the work. So asking the users browser to do the lifting is out of the question in my use case.

I think I'll just make a depends in my JSON file for the CPU version of @tensorflow/tfjs-node and tell users they can install the GPU version option for those who are brave enough to get it working. (it was a pain for me but it did it)

thanks again for the awesome package.

**Comment by vladmandic** [comment]
Oh, yes, getting CUDA libraries to bind properly to GPU drivers can be a pain.  
I'm just running quick tests, new version should be up shortly.

**Comment by meeki007** [comment]
If bundle is no longer supported do you have a reason you use [@tensorflow/tfjs](https://www.npmjs.com/package/@tensorflow/tfjs) instead of [@tensorflow/tfjs-node](https://www.npmjs.com/package/@tensorflow/tfjs-node) in the documentation?

I know the node version has allot less overhead. have not done any metrics myself.

**Comment by vladmandic** [comment]
I just changed that :)

**Comment by vladmandic** [comment]
new version is published & docs are updated  

- build is now done via script `build.js` instead of command line  
  much less prone to errors and also allows for quick changes to build settings  
- build is straight from typescript to bundle, skipping interim compile step (no more `/build` folder)  
- there is a virtual tfjs bundle created for each target so only ideal packages are imported for each target (see `src/tfjs/*`)  
  this way tfjs can also be swapped without needing to change all of the sources  
  notice that there are separate `node` and `node-gpu` targets as well  

the best thing, entire build takes about 2-3 seconds  

```text
npm run build

> @vladmandic/face-api@0.8.9 build /home/vlado/dev/face-api
> rimraf dist/* && node ./build.js
```
```json
2020-12-02 16:31:23 INFO:  @vladmandic/face-api version 0.8.9
2020-12-02 16:31:23 INFO:  User: vlado Platform: linux Arch: x64 Node: v15.0.1
2020-12-02 16:31:23 INFO:  Build: file startup all target: es2018
2020-12-02 16:31:23 STATE:  Build for: node type: tfjs: { imports: 1, importBytes: 39, outputBytes: 1042, outputFiles: 'dist/tfjs.esm.js' }
2020-12-02 16:31:23 STATE:  Build for: node type: node: { imports: 160, importBytes: 228038, outputBytes: 134190, outputFiles: 'dist/face-api.node.js' }
2020-12-02 16:31:23 STATE:  Build for: nodeGPU type: tfjs: { imports: 1, importBytes: 43, outputBytes: 1046, outputFiles: 'dist/tfjs.esm.js' }
2020-12-02 16:31:23 STATE:  Build for: nodeGPU type: node: { imports: 160, importBytes: 228042, outputBytes: 134198, outputFiles: 'dist/face-api.node-gpu.js' }
2020-12-02 16:31:23 STATE:  Build for: browserNoBundle type: tfjs: { imports: 1, importBytes: 1784, outputBytes: 244, outputFiles: 'dist/tfjs.esm.js' }
2020-12-02 16:31:23 STATE:  Build for: browserNoBundle type: esm: { imports: 160, importBytes: 227240, outputBytes: 131024, outputFiles: 'dist/face-api.esm-nobundle.js' }
2020-12-02 16:31:24 STATE:  Build for: browserBundle type: tfjs: { modules: 1045, moduleBytes: 3718721, imports: 7, importBytes: 1784, outputBytes: 1501677, outputFiles: 'dist/tfjs.esm.js' }
2020-12-02 16:31:24 STATE:  Build for: browserBundle type: iife: { imports: 162, importBytes: 1728673, modules: 576, moduleBytes: 1359851, outputBytes: 1903311, outputFiles: 'dist/face-api.js' }
2020-12-02 16:31:25 STATE:  Build for: browserBundle type: esm: { imports: 162, importBytes: 1728673, modules: 576, moduleBytes: 1359851, outputBytes: 1900836, outputFiles: 'dist/face-api.esm.js' }
```

**Comment by meeki007** [comment]
eating dinner. Will spin up a virtual box in 30min and give it a try and see how the install goes. I'll let you know after testing. Might be LATE LATE tonight.

**Comment by meeki007** [comment]
System OS: Ubuntu 20.04.1 LTS
NPM version: 6.14.8
node version: 12.20.0
node-red version: 1.2.6
@vladmandic/face-api": "^0.9.1",
@tensorflow/tfjs-node": "~2.7.0"

**Success!** 
for checks for CPU

![image](https://i.ibb.co/4FsDYyW/scrn1.png)

Only thing left is to finish / get the code working for the faceapi.nets.faceRecognitionNet to compare a image to a folder of reff images.

I'm not going to test GPU until I get my new [Jetson Nano](https://www.amazon.com/NVIDIA-Jetson-Nano-Developer-945-13450-0000-100/dp/B084DSDDLT/ref=sr_1_3?dchild=1&keywords=jetson+nano&qid=1606951902&sr=8-3). I'm to scared to poke at my CUDA stuff that's working now.

I'll let you know if there is an issue.

Thanks again

**Comment by vladmandic** [comment]
sounds good - let me know if you run into any issues.

i'm closing this one as resolved.
