### ISSUE TITLE
Can this lib use with RTSP Streaming Video From IP Camera?

### ISSUE THREAD

**Issue by Newbie-Programmer2001** [vladmandic/face-api#181]
I want to know can this lib use for face detection & recognition with RTSP Streaming Video From IP Camera?

**Comment by vladmandic** [comment]
check `https://github.com/vladmandic/stream-rtsp` - its not actively supported, but i wrote it explicitly so it can translate rtsp streams.

**Comment by Newbie-Programmer2001** [comment]
> check `https://github.com/vladmandic/stream-rtsp` - its not actively supported, but i wrote it explicitly so it can translate rtsp streams.

Thank you so much♥
