### ISSUE TITLE
Cant we use models from node modules and decrease models file size?

### ISSUE THREAD

**Issue by chaitanya71998** [vladmandic/face-api#184]
**Issue Description**
Greetings, thanks for your lib. i have two issues 
1. The models are need to be maintained in public folder
    - cant we use the models that are already there in nodemodules?
2. For my use case i am solving to build a face authentication web app using facematcher api. The models are of very high mb size,and are big blocker for authentication and getting to web app. 
    - how can we solve this? will the above using from node modules solve it?
    
**Steps to Reproduce**
1. In node modules 
![Screenshot from 2023-12-08 10-16-32](https://github.com/vladmandic/face-api/assets/46353549/86a98717-0a84-413c-ac54-6e71aac5e20e)

2. From network panel
 ![image](https://github.com/vladmandic/face-api/assets/46353549/8644bd3b-7ad7-4b95-8791-af2e6bc44c57)

**Expected Behavior**
Fast loading of models and finish authentication
**Environment
Web
- Module version?
  "@vladmandic/face-api": "1.7.12",

- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
  - esm - bundler(webpact)
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)?
  browsers

- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?
  webpack

**Comment by vladmandic** [comment]
i really don't understand what the ask is here - model size is what is it is regardless where its downloaded from.
you can download from cdn, copy to your public folder, expose node_modules directly - anything.

**Comment by chaitanya71998** [comment]
dont we have lower sized models, as these models are having very big file size

**Comment by vladmandic** [comment]
No. And this is considered quite small.
