### ISSUE TITLE
Detached EventHandlers when running on a Canvas

### ISSUE THREAD

**Issue by rebser** [vladmandic/face-api#187]
**Issue Description**

When running on a Canvas, EventHandlers are leaking.

**Steps to Reproduce**

Just run for example tinyFaceDetector on a Canvas.

**Expected Behavior**

face-api should not produce Detached EventHandlers

**Environment

Browser

**Comment by rebser** [comment]
Turns out the bug is in awaitMediaLoaded.

`if (media instanceof env.getEnv().Canvas || isMediaLoaded(media)) resolve(null);
`
doesn't do the trick because it resolves the Promise to null but doesn't return, meaning the EventHandlers for load and error are still  being added.

Solution:
`if (media instanceof env.getEnv().Canvas || isMediaLoaded(media)) {
      resolve(null);
      return;
    }`

**Comment by vladmandic** [comment]
great job tracing it down - do you wan to submit a pr or do you want me to patch it?
