### ISSUE TITLE
Support for TSC verbatimModuleSyntax

### ISSUE THREAD

**Issue by stephenjason89** [vladmandic/face-api#191]
I am getting a lot of ts error because types need to be imported with  `import type { ConvParams, SeparableConvParams } from '../common/index';` instead of
 `import { ConvParams, SeparableConvParams } from '../common/index';`

241 errors 
<img width="1049" alt="image" src="https://github.com/vladmandic/face-api/assets/3810177/cceab394-b855-4d28-bb00-b791cbcdfedc">

Thank you for maintaining this package

**Comment by vladmandic** [comment]
this is valid item, but to update entire repo to use strict `verbatimModuleSyntax` is non-trivial and I don't have time in the near-future.

however, if you want to submit PR, it would be welcome.
