### ISSUE TITLE
Obtaining weights from URL

### ISSUE THREAD

**Issue by SirVizzy** [vladmandic/face-api#197]
Given the fact that I host the models on a server. I would like to obtain the weights so I can load them in using `nets.model.load(weights)` myself (if this is even possible), without needing to rely on the built-in fetch functionality in face-api.

I'm struggling to figure out how to obtain the weights with a fetch request.

Edit: My bad. I believe this belongs in the Discussions section instead.

**Comment by vladmandic** [comment]
sorry for the late response, i'm not really actively maintaining this anymore - its a pretty old library.

`nets.model.load` takes `string` (url) or actual `Float32Array` - so yes, you can load weights manually and pass them to load method as float array. all models are in `/models`. but loading them is not a trivial op.

but not sure why are you looking at that? seems like simply changing model url prefix would be sufficient?
anyhow, closing this issue as its not really a product issue.
