### ISSUE TITLE
Error: The specified module cannot be found.

### ISSUE THREAD

**Issue by karelbyte** [vladmandic/face-api#199]
Hi, I'm creating a project in nestjs and I want to use its library, but when I install
npm install @tensorflow/tfjs-node
npm install @vladmandic/face-api
and import it into the project
import '@tensorflow/tfjs-node';
import * as faceapi from '@vladmandic/fase-api';
the project gives me the following error
```
node:internal/modules/cjs/loader:1465
return process.dlopen(module, path.toNamespacedPath(filename));
^

Error: The specified module cannot be found.
\\?\C:\Users\karel\apps\yappy-manager-biometric\node_modules\@tensorflow\tfjs-node\lib\napi-v8\tfjs_binding.node at Module._extensions..node (node:internal/modules/cjs/loader:1465:18) at Module.load (node:internal/modules/cjs/loader: 1206:32) at Module._load (node:internal/modules/cjs/loader:1022:12) at Module.require (node:internal/modules/cjs/loader:1231:19) at require (node:internal/modules/helpers:179:18) at Object.<anonymous> (C:\Users\karel\apps\yappy-manager-biometric\node_modules\@tensorflow\tfjs-node\dist\index.js:72:16) at Module._compile (node:internal/modules/cjs/loader:1369:14) at Module._extensions..js (node:internal/modules/cjs/loader:1427: 10) at Module.load (node:internal/modules/cjs/loader:1206:32) at Module._load (node:internal/modules/cjs/loader:1022:12) { code: 'ERR_DLOPEN_FAILED' } Node.js v20.12.0 
```
The reality is that if I go to that place in the node_module, if the files are there, I have it reviewing and super reviewing

I have installed and uninstalled the package and I still get the error when running the project, which is in nestjs.

Do you have any suggestions or clues about this error? Thank you very much

**Comment by vladmandic** [comment]
there's an incompatibility between your nodejs and @tensorflow/tfjs-node package, you need to find versions that work.
sorry, i don't have any nestjs experience and cannot offer more assistance.
furthermore, i'll be moving this project to maintenance mode - its old and last refresh will be considered final.
