### ISSUE TITLE
Facial recognition example? Contact info? and you now have a dependent on NPM 

### ISSUE THREAD

**Issue by meeki007** [vladmandic/face-api#23]
<b>Facial recognition example:</b>

I've tried many times now to get a vanilla nodeJS environment to work with your example flow but its not been a priority as I've been busy with my own repo. However I do have a working version of facial recognition that works with your face-api in node-red.

If you take a look at my [facial-recognition.js](https://github.com/meeki007/node-red-contrib-facial-recognition/blob/main/facial-recognition.js) line in code 771 to 828.  It allows a user to just name the folder and put images into it. Thought you might find this helpful.

<b>Your Contact info </b>

I wanted to email you a link to a server running the node-red version of Facial recognition based on your face-api so you could play around with it if you wanted, also so i did not have to blast/treat your issues section as a message board.
I think I found your Instagram do you want me to send you a message there?

<b>you now have a dependent on NPM</b>
[https://www.npmjs.com/browse/depended/@vladmandic/face-api](https://www.npmjs.com/browse/depended/@vladmandic/face-api)

I'm proud to be the first one on the list

Thanks again,

Meeki

I'm just so tickled i got this working:

![image.jpg](https://raw.githubusercontent.com/meeki007/node-red-contrib-facial-recognition/main/doc/image.jpg)

**Comment by vladmandic** [comment]
> I wanted to email you a link to a server running the node-red version of Facial recognition based on your face-api
> so you could play around with it if you wanted, also so i did not have to blast/treat your issues section as a message board.

I'll definitely check it out! Never played with `node-red` myself.

> I think I found your Instagram do you want me to send you a message there?

Yes, you have :)

On the topic of non-issue messages, **github** recently allows for **discussions** & i've just enabled it (see top menu line, close to issues)!
