### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "@tensorflow/tfjs/dist/index.js". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by umitkacar** [vladmandic/face-api#24]
Thank you for face-api.js with tfjs-2.7.0,

to use non-bundled version:
import * as faceapi from 'dist/face-api.esm-nobundle.js';

There is an error.

Uncaught TypeError: Failed to resolve module specifier "@tensorflow/tfjs/dist/index.js". Relative references must start with either "/", "./", or "../".

How do I fix it?

**Comment by vladmandic** [comment]
`face-api.esm-nobundle.js` is intended to be used with bundlers (e.g, `esbuild`, `webpack`, `parcel`, `rollup`) so they can resolve dependencies. it cannot be used as direct import without bundlers - i've corrected the documentation to reflect that.

so if you're not using a bundler, it is recommended to use `face-api.esm.js` which pre-bundles latest version of `tfjs` (as of today it has been updated to 2.8.0).

now, if you have a requirement to use a specific version of tfjs and bundled one does not fit your needs, you can easily create a custom bundle - simply edit `src/tfjs/tf-browser.js` (this is basically a virtual package exactly for purpose to be able to swap-out `tfjs` in a single step) to include whichever version of  `tfjs` you wish to use and run `npm run build` to create a `face-api` bundle.

**Comment by umitkacar** [comment]
Thank you. I started `face-api.esm.js`. It has tfjs 2.7.0. It is enough for me. 

 `import` * as faceapi from './dist/face-api.esm.js';
