### ISSUE TITLE
There is a leak memory: faceapi.extractFaceTensors and  faceapi.extractFaces

### ISSUE THREAD

**Issue by umitkacar** [vladmandic/face-api#25]
```js
faceapi.tf.setBackend('webgl');
faceapi.tf.enableProdMode();
faceapi.tf.ENV.set('DEBUG', false);
faceapi.tf.ready();

.......
const videoTensor = await faceapi.tf.browser.fromPixels(video);
const detections = await faceapi.detectAllFaces(videoTensor, new faceapi.SsdMobilenetv1Options({ minConfidence: minScore, maxResults }));
const faceImages = await faceapi.extractFaceTensors(videoTensor, detections);

await videoTensor.dispose();
await faceImages[0].dispose();

```

I follow my GPU memory. I detect a leak memory. Maybe we can use x.dispose(); I tried it, but this problem continue...
I checked faceapi.detectAllFaces function. There is not any leak. I think faceapi.extractFaceTensors function.
How can I fix it?

**Comment by vladmandic** [comment]
Monitoring GPU memory does not necessarily mean there is a leak as GPU memory is released by garbage collection that happens later, not immediately upon completion. 

You should monitor `faceapi.tf.engine().memory().numTensors` before and after and do it for several iterations. If number of active tensor is increasing, then there is a memory leak. If yes, please post full reproduction code.

And a trivial question - are you sure that `faceImages` array in your case has a length of 1?

**Comment by vladmandic** [comment]
I just tried with 100 images and detected no leak:
```js
      console.log('numTensors before:', faceapi.tf.engine().state.numTensors);
      const videoTensor = await faceapi.tf.browser.fromPixels(canvas);
      const detections = await faceapi.detectAllFaces(videoTensor, new faceapi.SsdMobilenetv1Options({ minConfidence: minScore, maxResults }));
      const faceImages = await faceapi.extractFaceTensors(videoTensor, detections);
      console.log('faceImages', faceImages);
      videoTensor.dispose();
      faceImages.forEach(faceTensor => faceTensor.dispose());
      console.log('numTensors after:', faceapi.tf.engine().state.numTensors);
```

**Comment by umitkacar** [comment]
I will check it. Then, I will return you.

**Comment by umitkacar** [comment]
```js

import * as faceapi from './dist/face-api.esm.js';

const video = document.getElementById("video");

faceapi.tf.setBackend('webgl');
console.log(faceapi.tf.getBackend());
faceapi.tf.enableProdMode();
faceapi.tf.ENV.set('DEBUG', false);
faceapi.tf.ready();

// Face Detection CONFIG
const minScore = 0.8;
const maxResults = 10; // maximum 
const localHost = "http://127.0.0.1:5503";

Promise.all([
    faceapi.nets.ssdMobilenetv1.loadFromUri(localHost + "/model"),
]).then(startCamera);

function startCamera() {
    navigator.getUserMedia({
            video: {}
        },
        stream => (video.srcObject = stream),
        err => console.log(err)
    );
}

video.addEventListener("play", async() => {
    const canvas = await faceapi.createCanvasFromMedia(video, { minConfidence: 0.8 });
    document.body.append(canvas);
    const boxSize = {
        width: video.width,
        height: video.height
    };
    faceapi.matchDimensions(canvas, boxSize);
    setInterval(async() => {

        const videoTensor = await faceapi.tf.browser.fromPixels(video);
        const detections = await faceapi.detectAllFaces(videoTensor, new faceapi.SsdMobilenetv1Options({ minConfidence: minScore, maxResults }));
        canvas.getContext("2d").clearRect(0, 0, canvas.width, canvas.height);
        const resizedDetections = await faceapi.resizeResults(detections, boxSize);
        faceapi.draw.drawDetections(canvas, resizedDetections);
        const faceImages = await faceapi.extractFaceTensors(videoTensor, detections);

        videoTensor.dispose();
        faceImages.forEach(faceTensor => faceTensor.dispose());

        console.log(faceapi.tf.engine().memory().numTensors);

    }, 100);
});
```
I use Ubuntu 18.04. I watch GPU memory using bash command "watch -n 0,2 nvidia-smi". You can paste this command in Terminal. There is a leak.

**Comment by umitkacar** [comment]
```html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Face Detection</title>
    <script defer src="index.js" type="module"></script>
    <style>
        body {
            margin: 0;
            padding: 0;
            width: 100vw;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        canvas {
            position: absolute;
        }
        
        video {
            box-shadow: -2px 12px 20px 0px rgb(0, 0, 0);
        }
    </style>
    <div id="outputImage"></div>
</head>

<body>
    <video id="video" width="640" height="480" autoplay muted></video>
</body>

</html>

```

Also, this is index.html

**Comment by vladmandic** [comment]
It's possible there is a leak, but that doesn't prove it - like i said, GPU memory does not get deallocated as soon as tensor is disposed, it goes into a pool and waits for browser garbage collection to kick in which can be much later.

Try couple of things:
- Process xx frames and then stop processing without exiting app, let it sit idle for couple of seconds.  
  Lets see if garbage collection kicks in.  
- Capture output of `faceapi.tf.engine().state` output periodically to monitor for changes
- Set flag to run with aggresive memory deallocation  
  This will slow down detection by quite a lot as shaders need to be re-uploaded on each frame instead of being reused).
  `faceapi.tf.ENV.set('WEBGL_DELETE_TEXTURE_THRESHOLD', 0);`

**Comment by vladmandic** [comment]
btw, when posting code, it's much better to create a gist <https://gist.github.com/> and just share link to it

**Comment by umitkacar** [comment]
I use  faceImages as a async function. So, I solved this problem using below command. 
Your supports have been very helpful. Thank you. I am closing it.
```js
faceapi.tf.engine().startScope();
   // ALL CODES
faceapi.tf.engine().endScope();
```

**Comment by Wursteintopf** [comment]
> 
> 
> I use faceImages as a async function. So, I solved this problem using below command. Your supports have been very helpful. Thank you. I am closing it.
> 
> ```js
> faceapi.tf.engine().startScope();
>    // ALL CODES
> faceapi.tf.engine().endScope();
> ```

Although this issue is already closed I just wanted to mention: you just provided me the answer to hours of headache. Thanks a lot <3

**Comment by vladmandic** [comment]
im glad your problem is gone, but i wish we got to the bottom of this as wrapping faceapi into a scope hides the issue, doesnt resolve it internally - but the diagnostic info was never provided.

**Comment by Wursteintopf** [comment]
If you need any diagnostic info about my specific use case feel free to ask me anytime or have a look at my code: https://github.com/Wursteintopf/YouLys/blob/main/src/backend/FaceApi/FaceApi.ts

I call my `detectFaces()` function a few hundred times and the number of tensors was constantly increasing (before wrapping it into a scope), for some reason they weren't garbage collected. I did not specifically dispose them though, my method is very close to the original nodejs example.

**Comment by vladmandic** [comment]
@Wursteintopf that's not a leak, that's due to your design:
- you're loading weights each time `detectFaces` is called  
- you're creating new instance of options each time `detectFaces` is called  

do it once in an init function and reuse options variable once its created.

**Comment by Wursteintopf** [comment]
Oh, yeah, you're right, thats definitely not clever designed. I still dont really get, why that increases the amount of tensors, if I dont wrap it in a scope. Shouldn't the old tensors be removed as soon the `detectFaces` function ends? I dont even call the function asyncronously but let one pass before starting the next one.

**Comment by vladmandic** [comment]
no, `tfjs` never deallocates tensors automatically - its not like normal js.

**Comment by vladmandic** [comment]
why? you only need to deallocate tensors you create  
if you load weights and create options object once, it will use that memory and never grow  
and what happens inside faceapi is deallocated by faceapi itself  
you'd only need to wrap it if you for some reason want to "unload" weights eventually, but i don't see the reason for that

**Comment by Wursteintopf** [comment]
Aaaah, alright. Yeah, understood. Thanks a lot for your explanations!

**Comment by vladmandic** [comment]
one more note, monitoring gpu memory can be misleading as tfjs performs its internal caching and garbage collection  
so gpu memory usage can grow if there is free memory for better caching, but it doesnt mean its leaking  
(there are ways to force tfjs garbage collection, but thats a different story)

to monitor for any leaks, just look at the value of `faceapi.tf.engine().memory().numTensors` - its 0 on startup, then grows when models and weights are loaded and stays constant after each `detectFace`. if it grows, then its a leak.

**Comment by jeffreykthomas** [comment]
Hello, repo is working great for me, except I seem to have a similar issue as this user. I've tried to follow your suggestions listed here, but not sure if I have understood them all accurately. 

Main issue is that there are tensors created that my code is not disposing... 

The numTensors increases with each frame by 6. If you look below in the gist I attached, there are three calls that I have to .dispose(), and they do dispose those tensors, but there seems to be 6 other tensors created in each call that aren't disposed.  (if I comment out those .dispose() lines, numTensors increases by 9 each frame, versus 6 when they're run)

Do you know what I might be missing?

https://gist.github.com/jeffreykthomas/65fab407dfd7155c3eb4bdfd7143dedc

**Comment by vladmandic** [comment]
```js
                  let faceImage = tf.tidy(() => {
                    return tf.image.resizeBilinear(faceImages[0], [64, 64])
                  })
                  faceImage = faceImage.expandDims(0)
                  faceImage = faceImage.div(tf.scalar(255))
```

last two lines overwrite same variable so previous value is never disposed.
when working with tensors, i'd advise in general never re-use variable, always use `const` definitions - that way you'll know.

quick solution is just to move them inside `tf.tidy` block.

**Comment by jeffreykthomas** [comment]
Thank you for the quick reply and guidance!
