### ISSUE TITLE
How will my web provide it all (WASM + SIMD + MULTI-THREAD) ?

### ISSUE THREAD

**Issue by umitkacar** [vladmandic/face-api#29]
I tried Google-Chrome, Firefox.
There is SIMD problem for Google-Chrome:
```js
DEBUG: false
IS_BROWSER: true
IS_NODE: false
IS_TEST: false
PROD: true
WASM_HAS_MULTITHREAD_SUPPORT: true
WASM_HAS_SIMD_SUPPORT: false
```
My google-chrome version is 87. 
How can I provide SIMD for Google-chrome?

**Comment by vladmandic** [comment]
check out <https://github.com/vladmandic/human/wiki/Backends>

**Comment by umitkacar** [comment]
Thank you. I tried for Google-Chrome. It is running:
```js
DEBUG: false
IS_BROWSER: true
IS_NODE: false
IS_TEST: false
PROD: true
WASM_HAS_MULTITHREAD_SUPPORT: true
WASM_HAS_SIMD_SUPPORT: true
```
For Firefox
SIMD is running, but multithread is disabled. How can I enable multi-thread for Firefox?

```js
DEBUG: false
IS_BROWSER: true
IS_NODE: false
IS_TEST: false
PROD: true
WASM_HAS_MULTITHREAD_SUPPORT: false
WASM_HAS_SIMD_SUPPORT: true
```

**Comment by vladmandic** [comment]
Firefox doesn't have a full threaded implementation yet, it's only available in debug nightly builds.  
But SIMD is a major improvement and I definitely recommend it.

**Comment by umit-ai** [comment]
I tried Firefox Nightly. Multi-thread is still false.

`js 
WASM_HAS_MULTITHREAD_SUPPORT: false`

**Comment by umitkacar** [comment]
I tried Firefox Nightly. Multi-thread is still false. How can I enable it?

WASM_HAS_MULTITHREAD_SUPPORT: false

**Comment by vladmandic** [comment]
that's really a question for firefox, not for face-api.  
looking around, seems like firefox now requires special CORS settings on web server before client is allowed to use multi-threading.
<https://dzone.com/articles/webassembly-threads-in-firefox>

but other than that, i cannot help with this - i can support whatever is supported in browser, not more than that :)
