### ISSUE TITLE
face-api.esm-nobundle.js seems including tensorflow

### ISSUE THREAD

**Issue by vincentwinkel** [vladmandic/face-api#31]
I understood we had to specifically use `face-api.esm-nobundle.js` in order to be able to use tensorflow externally.
But here are my vendors before:
<img width="765" alt="Screenshot 2021-01-06 at 22 19 43" src="https://user-images.githubusercontent.com/1402505/103821036-b4ce2c00-506d-11eb-953a-9e5cf22aa19c.png">

Then when I import face-api:
```js
import * as faceapi from '@vladmandic/face-api/dist/face-api.esm-nobundle.js';
```
<img width="1066" alt="Screenshot 2021-01-06 at 22 20 25" src="https://user-images.githubusercontent.com/1402505/103821119-d92a0880-506d-11eb-98f6-bd6415e606ad.png">

Did I understand something wrong?

**Comment by vladmandic** [comment]
FaceAPI *requires* `@tensorflow /tfjs` (by means of a re-export in `src/tfjs/tf-browser.ts`) so it shows under dependencies no matter what.  
Difference is bundled version pre-packages it and no-bundle version requires that user provides it before loading FaceAPI.  

Just take a look at size differences: `face-api.esm.js` is 1.7MB while `face-api.esm-nobundle.js` is 127KB.

**Comment by vincentwinkel** [comment]
Ok my bad, I get it, thanks.
