### ISSUE TITLE
Takes long for first inference (excluding model load time)

### ISSUE THREAD

**Issue by rjdp** [vladmandic/face-api#36]
@vladmandic any tips for making first inference faster? Thanks

**Comment by vladmandic** [comment]
which part is taking too long?
- Loading of weights? This can be accelerated to near-zero by caching weights client side. I personally like to use `serviceWorker` caching features for that although I haven't implemented it in the included demo.
- Model warmup? If using `WASM` backend, this is near-zero. But if using `WebGL` backend (which I prefer in general), there is significant time to initialize and compile GL shaders. You cannot eliminate it, but you can reduce impact by embedding a very low resolution image in your app and performing a inference in the background on it first - once it's complete, there will be no further delays when you want to run inference on your actual data.

**Comment by rjdp** [comment]
model warmup (the first call to .detectAllFaces / .detectSingleFace), Thanks for the suggestion I had tried same (its of little help as I need call face detection as soon as page loads). Thanks for the detailed writeup :)

**Comment by vladmandic** [comment]
...its just the way `webgl` backend works, not specific to `face-api` at all.
if i come up with some alternative ideas, i'll update the thread.
