### ISSUE TITLE
TF.js Error: TensorList shape mismatch: Shapes -1 and 3 must match

### ISSUE THREAD

**Issue by umitkacar** [vladmandic/face-api#37]
Can you update `face-api` (`tfjs-3.0.0`) ?

There is an update below for `tfjs-3.0.0`

https://github.com/tensorflow/tensorflow/issues/46925

I use other model with `face.api`. I have same problem.
I use this model below.
`import * as faceapi from './dist/face-api.esm.js';`
I need to this model for only client-side.

Thank you in advance

**Comment by umitkacar** [comment]
You can see this update below for tfjs-3.0.0.

https://github.com/tensorflow/tfjs/pull/4657/commits/1de9588519608bb11cd0b261af1f4de1c0eaa92e
https://github.com/tensorflow/tfjs

**Comment by vladmandic** [comment]
i'm curious on the error you're getting - can you share your code and actual error backtrace?
i'm curious on the error you're getting - can you share your code and actual error backtrace?


i'm curious how did you end up with this error - can you publish your reproduction code?

anyhow, i've updated `face-api` with tfjs 3.0.0 some 10 days ago.  
i took a look at the pull request you've mentioned and it's not yet in a published version of `tfjs` - as soon as `tfjs` 3.0.1 is released, i'll publish updated version of `face-api`

btw, you can re-build `face-api` pretty fast:
```shell
git clone https://github.com/vladmandic/face-api
cd face-api
npm install
# now modify any code or used packages
npm run build
# rebuild only takes few seconds and results are in /dist folder
```

but for this issue, you'd need to clone `tfjs` and rebuilt id manually as well using `yarn run build-deps` and then link `face-api` to use your custom build of `tfjs` using `npm install <path-to-tfjs-package>` for every `tfjs` module.  

it's not a problem to do so, but i cannot publish updated `face-api` based on unpublished version of `tfjs`

**Comment by umitkacar** [comment]
I will do what you say and give you feedback.

My goal is to make the sample detector in the link below:

https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb

Then I will do an ear detection application. My doctoral thesis was on ear recognition. I want to merge it with your `face.api` in the future.

**Comment by vladmandic** [comment]
interesting...

may i suggest you take a look at <https://github.com/vladmandic/human>?  
it's much newer than `face-api` and what you mention is closer to a modular concept it has, not unlike how `facemesh` model is augmented by additional `iris` model.

regarding rebuilding `face-api` with custom-built `tfjs` - once you have your `tfjs` modules ready, you don't need to mess with installing them into `face-api`, you can directly modify `src/tfjs/tf-browser.js` - it exists for exact purpose so version of tfjs can be replaced easily and in one place.

**Comment by umitkacar** [comment]
Yes, I have looked before. It's a really good project. I think it will be much more perfect if you shoot a video explaining this project. (modularity, additions, code explanation, updates ...) It will be proud for me to contribute to this project with ear detection. Thank you for your open source support.

**Comment by vladmandic** [comment]
good idea!

**Comment by umitkacar** [comment]
I've tried a lot but the problem persists. I will wait to update.

**Comment by vladmandic** [comment]
as soon as tfjs 3.0.1 is published, i'll run tests and update the package.

**Comment by umitkacar** [comment]
It is great. I look forward to your update. Thank you again.

`https://github.com/tensorflow/tfjs/tree/tfjs_3.1.0`

**Comment by umitkacar** [comment]
I tried it. It is working. I am waiting for your update.

Perfect!

https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.1.0/dist/tf.min.js

**Comment by vladmandic** [comment]
updated version is published: FaceAPI 0.12.7 TensorFlow/JS 3.1.0

**Comment by umitkacar** [comment]
Thank you. I will check it.

**Comment by vladmandic** [comment]
closing the issue as package upgrade has been completed

**Comment by umitkacar** [comment]
I checked it. Everything works fine. Thank you.
