### ISSUE TITLE
import * as seedrandom from 'seedrandom

### ISSUE THREAD

**Issue by dataCoderX10** [vladmandic/face-api#41]
**Issue Description**
I got a problem about "import * as seedrandom from 'seedrandom';"

**Steps to Reproduce**
git clone https://github.com/vladmandic/face-api
cd face-api
npm install
npm run build
npm run dev 

**Expected Behavior**
I think it should run correctly, see my face was detected with the camera

**Environment
- FaceAPI version
version is the lastest face-api version from vladmandic
- FaceAPI module used (e.g. `face-api`, `face-api.esm`, `face-api.esm-nobundle`)
I just wanna start the demo locally
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 86)
browser version is chrome  89.0.4389.82 and the nodejs version is v12.18.3

- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)
os version is Windows7
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)
no packager

the error message : 
```
         > node_modules/@tensorflow/tfjs-data/dist/dataset.js:19:28: error: Could not resolve "seedrandom" (mark it as external to exclude it from the bundle)
            19 │ import * as seedrandom from 'seedrandom';
               ╵                             ~~~~~~~~~~~~
        
         > node_modules/@tensorflow/tfjs-data/dist/iterators/lazy_iterator.js:19:28: error: Could not resolve "seedrandom" (mark it as external to exclude it from the bundle)
            19 │ import * as seedrandom from 'seedrandom';
               ╵                             ~~~~~~~~~~~~
        
        2021-03-16 09:26:04 STATE:  Monitoring: [ 'package.json', 'demo', 'src', [length]: 3 ]
        2021-03-16 09:26:04 ERROR:  Build error [
          {
            "location": {
              "column": 28,
              "file": "node_modules/@tensorflow/tfjs-data/dist/dataset.js",
              "length": 12,
              "line": 19,
              "lineText": "import * as seedrandom from 'seedrandom';",
              "namespace": ""
            },
            "notes": [],
            "text": "Could not resolve \"seedrandom\" (mark it as external to exclude it from the bundle)"
          },
          {
            "location": {
              "column": 28,
              "file": "node_modules/@tensorflow/tfjs-data/dist/iterators/lazy_iterator.js",
              "length": 12,
              "line": 19,
              "lineText": "import * as seedrandom from 'seedrandom';",
              "namespace": ""
            },
            "notes": [],
            "text": "Could not resolve \"seedrandom\" (mark it as external to exclude it from the bundle)"
          }
        ]
```

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
sorry about that, made a mistake during publishing of latest version  
new version `1.1.3` is now published  

btw, not related, but you don't need to run `npm run build` before `npm run dev` - those two are interchangable, it's one or the other: `build` creates a production bundles and updates docs and types and `dev` creates dev bundle (and in your case overwrites production bundle you created in the step before)

**Comment by vladmandic** [comment]
@dataCoderX10 any updates?

**Comment by vladmandic** [comment]
closing as resolved
