### ISSUE TITLE
Time taken on first run much higher than consequent runs

### ISSUE THREAD

**Issue by mayankagarwal-cf** [vladmandic/face-api#44]
**Issue Description**:
On running the browser API, the time taken to calculate the first encoding is about 30x more than the consequent ones in the same run and about 15x on consequent runs on the same tab. . Can all of this be attributed to cache misses or can loading be made better even if it takes more time? 

**Steps to Reproduce**:
In the `demo` folder, add two files with pasted content:
`TimeMultipleRuns.js`
```
import * as faceapi from '../dist/face-api.esm.js';


const modelPath = "../model";


await faceapi.tf.setBackend('webgl');
await faceapi.tf.enableProdMode();
await faceapi.tf.ENV.set('DEBUG', false);
await faceapi.tf.ready();

const minScore = 0.3; // minimum score
const maxResults = 10; // maximum number of results to return

const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options({
    minConfidence: minScore,
    maxResults
});

document.getElementById("run").addEventListener("click", run);

let imgElement;

async function run(){
        
    await faceapi.nets.ssdMobilenetv1.load(modelPath);
    await faceapi.nets.faceLandmark68Net.load(modelPath);
    await faceapi.nets.faceRecognitionNet.load(modelPath);

    console.log("Models loaded")

    const inputElement = document.getElementById("file");
    const file = inputElement.files[0];

    if(FileReader){ //file reader support
      let fr = new FileReader();
      fr.onload = async function () {

          imgElement = new Image();
          imgElement.onload = ImgOnLoad;
          imgElement.src = fr.result;


      }
      fr.readAsDataURL(file);
    }
    else{
      console.log("File reader not supported")
    }
    console.log(inputElement.files[0]);


}

async function ImgOnLoad(){
    let canvas = document.getElementById("canvas")
    canvas.width = imgElement.width;
    canvas.height = imgElement.height;
    let ctx = canvas.getContext("2d");
    ctx.drawImage(imgElement,0,0);



  	const encoding = await calculateEncoding(canvas);

 	console.log(encoding);
}


async function calculateEncoding(img){


      let result;

      for(let i = 0; i < 10; ++i){

          const startTime = performance.now();

          //We want to detect the best face in each file
          result = await faceapi.detectSingleFace(img, new faceapi.SsdMobilenetv1Options(optionsSSDMobileNet))
          .withFaceLandmarks()
          .withFaceDescriptor()

          const endTime = performance.now();

          console.log(`Time for run ${i + 1} in ms: ${endTime - startTime}`);

      }

      //only if face found
      if(result != undefined)
          return result.descriptor;
      else 
        return undefined;

}
```
`TimeMultipleRuns.html`
```
<!DOCTYPE html>
<html>
<head>
    <script src="./TimeMultipleRuns.js" type="module"></script>

</head>
<body>

  <input type="file" id="file" name="file"/><br><br>

    <button id = "run">Run</button><br><br>
    <canvas id="canvas" width="640" height="480"></canvas>


</body>
</html>
```

**Expected Behavior**:
Even if load() takes more time, runs should only be doing calculation on values already loaded in memory

**Environment**:

- Module version : Latest clone of the repo
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89) : Chrome 89
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10) : Ubuntu 20  on x64

**Comment by vladmandic** [comment]
> On running the browser API, the time taken to calculate the first encoding is about 30x more than the consequent ones in the same run and about 15x on consequent runs on the same tab. 

That's how TFJS with `WebGL` backend works for all models, not specific to `FaceAPI`  
All ML operations in the model are translated into GL shader operations which take time to compile and upload to GPU   
(I have some more complex projects where this initial time is above a minute)  

If you want fast startup, you can use `WASM` backend instead (initialization time there is zero), but then you get fast execution on CPU without full GPU acceleration. So it's fast on initial, but it doesn't speed up later.

> Can all of this be attributed to cache misses or can loading be made better even if it takes more time?

My typical approach for this is to have one test image with face included in the project and pass it for detection without ever showing it. So only when one initial detection has completed, I display "ready" to user  

I'm closing this issue as by-design, but feel free to continue the thread with any question

**Comment by mayankagarwal-cf** [comment]
Ah, that makes sense. I had a few questions I was hoping you could answer:
1. So once these shader operations are uploaded to GPU, how are they not required in consequent runs. Are they cached in some way? Can you point me to a resource where I can read up more on this

2. I was trying to see if this works on a very low-end compute device since you are using a 12MB model version.  I have a device which just has adreno 304 integrated gpu and 2 GB Ram (a lenovo yt3-850m to be specific). But the first encoding is never calculated at all. I had left it for an hour. The compiling can't be that slow, do you think it's a webgl problem as adreno 304 is a very entry level graphics card

**Comment by vladmandic** [comment]
> So once these shader operations are uploaded to GPU, how are they not required in consequent runs. Are they cached in some way? Can you point me to a resource where I can read up more on this

They are cached and they stay in GPU until browser determines it wants to perform garbage collection inside GPU which by default almost never happens  

Think of those shaders as tensor functions converted to GPU way of doing math  
For example, think of an image as being 2D array of RGB values. If I want to reduce brightness by some percentage, I want to divide every value by some number - but for large image that is a huge double loop and I don't want to do that in JavaScript or any language like that.

but I can ask TFJS to do that and TFJS will create a GL shader program that looks like it's its creating triangles (every GL operation in on triangles) and then darkening each triangles (oversimplified) so large matrix division is performed on GPU :)
And now data is already in GPU, so next tensor operation can be done even faster

So functions (almost) always stay and only initial data is uploaded for each image or frame and then results are downloaded from GPU

> The compiling can't be that slow, do you think it's a webgl problem as adreno 304 is a very entry level graphics card

No, it can't be that slow. Most likely you're getting some exception error in the browser, but not looking for it  
Typical exception would be: `Uncaught Error: Failed to compile fragment shader.`

But on a low end GPU-s, there is no advantage of using GPU acceleration via `WebGL` backend  
Best to switch to `WASM` backend and run detection using CPU  
(WASM is still much more optimized for tensor operations than doing them manually in JavaScript)

**Comment by mayankagarwal-cf** [comment]
Thanks a ton for the detailed explanation :). 

Oh, yes. it says `The browser supports webgl 2, but is disabled or unavailable. Sometimes, this is the result of older video drivers being rejected by the browser. Try updating video drivers`. Found the bug. Yay:). I was just curious to try this on all devices. It worked on all the 9 devices I have but this haha. 

I tried wasm. It takes around 23-30 seconds for each run :p.But yeah, something is better than nothing

**Comment by mayankagarwal-cf** [comment]
One another thing, is there a way to get tfjs working with webgl1? I found this comment which says : https://github.com/tensorflow/tfjs/issues/4284#issuecomment-731357063, tfjs could possibly work with webgl 1 but I can't find any source as to how to make it the target

**Comment by vladmandic** [comment]
fist, it would require a custom version of tfjs that binds to webgl v1 context  
i could do that as a test, but i'd never ship a library based on a custom version of tfjs as then i'd have to maintain that fork of tfjs as well  

then it would be the question of compatibility - webgl v2 introduces many operations that don't exist in webgl v1 - very low chance of success without major reimplementation of some gl shader functions  

all-in-all, possible but far outside of the scope here

**Comment by vladmandic** [comment]
regarding cpu execution
- with wasm, did you enable simd extensions?  
  that allows wasm to use all cpu threads, not just single thread
  and its disabled by default in current browsers
  for example, enable "WebAssembly SIMD" support in <chrome://flags>
- it would probably be faster using nodejs than in browser using wasm  
  as there is no overhead of loading wasm llvm and exeuciting inside llvm

**Comment by mayankagarwal-cf** [comment]
That makes a lot of sense. Thanks for the information :). Thanks for clarifying!. 

Oh, I wasn't aware of this, I'll try those out. Thanks again!

**Comment by mayankagarwal-cf** [comment]
Update: Enabling SIMD has a whopping effect on laptop (my laptop supports avx2), each run is around 2x slower than webgl and around 16-20x faster than not using SIMD
On the tablet which has Cortex a-7 arm neon support, it's around 1.5x faster than not using SIMD.
