### ISSUE TITLE
 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application / wasm'

### ISSUE THREAD

**Issue by deylyn** [vladmandic/face-api#48]
this happens to me sometimes and sometimes it does not happen to me:

vendor.5719bdd2.js: 14910 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

14.337f99a0.js: 1 Detect Error: Error: TinyYolov2 - load model before inference

vendor.5719bdd2.js: 195 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application / wasm'.

falling back to ArrayBuffer instantiation

I work with vue

import * as faceapi from "@vladmandic/face-api/dist/face-api.esm.js";
var backendWasm = await this.backendWasm();
Promise.all([faceapi.nets.tinyFaceDetector.loadFromUri("/statics/models")]);

    this.video.addEventListener(
        "play",
        function() {
          self.canvasFace = document.getElementById("c1");
          self.displaySize = {
            width: self.videoWidth,
            height: self.videoHeight
          };
          faceapi.matchDimensions(self.canvasFace, self.displaySize);
          self.canvasText = document.getElementById("c2");
          self.timerCallback();
        },
        false
      );

   timerCallback: async function() {
      console.log('timer');
      if (this.video.paused || this.video.ended) {
        return;
      }
      let box = {};
      let xBox;
      let boxArea;
      let anchBoundBox;
      let altBoundBox;
      let yBox;
      if (this.$q.screen.xs) {
        box = { x: 50, y: 37.5, width: 200, height: 225 };
        xBox = 10;
        yBox = box.y + 25;
        boxArea = 20000;
      } else {
        box = { x: 75, y: 37.5, width: 150, height: 225 };
        xBox = box.x - 35;
        yBox = box.y + 45;
        boxArea = 21000;
      }

      var lenghtx = box.x + box.width;
      var lenghty = box.y + box.height;
      // see DrawBoxOptions below
      const drawOptions = {
        lineWidth: 2,
        boxColor: "#23b2be"
      };
      const drawBox = new faceapi.draw.DrawBox(box, drawOptions);
      drawBox.draw(this.canvasFace);
      let inputSize = 128;
      let scoreThresholds = 0.2;
      let self = this;
      faceapi
        .detectAllFaces(
          self.video,
          new faceapi.TinyFaceDetectorOptions({ inputSize, scoreThresholds })
        )
        .then(result => {
          const resizedDetections = faceapi.resizeResults(
            result,
            self.displaySize
          );

          if (resizedDetections[0]) {
            if (self.$q.screen.xs) {
              anchBoundBox = resizedDetections[0].box["width"] - 40;
              altBoundBox = resizedDetections[0].box["height"] - 35;
            } else {
              anchBoundBox = resizedDetections[0].box["width"] - 15;
              altBoundBox = resizedDetections[0].box["height"] - 15;
            }
            if (
              anchBoundBox + resizedDetections[0].box["x"] > lenghtx ||
              resizedDetections[0].box["x"] < xBox ||
              resizedDetections[0].box["y"] < yBox ||
              altBoundBox + resizedDetections[0].box["y"] > lenghty
            ) {
              self.validCentered = false;
              self.textAlert = "Centre su rostro";
              self.paintBoxAlert(self.textAlert);
              self.$emit("detect-centered", false);
            } else {
              self.validCentered = true;
              self.$emit("detect-centered", true);
            }
            if (resizedDetections[0].box.area > boxArea) {
              self.validProximity = true;
              self.$emit("detect-proximity", true);
            } else {
              self.textAlert = "Acerque su rostro";
              self.paintBoxAlert(self.textAlert);
              self.validProximity = false;
              self.$emit("detect-proximity", false);
            }
          } else {
            self.validProximity = false;
            self.validCentered = false;
          }
          if (self.validCentered && self.validProximity) {
            self.canvasText
              .getContext("2d")
              .clearRect(0, 0, self.canvasText.width, 20);
          }
          requestAnimationFrame(() => self.timerCallback());
          return true;
        })
        .catch(err => {
          console.error(`Detect Error: ${err}`);
          return false;
        });
      return false;
    },

**Comment by vladmandic** [comment]
> vendor.5719bdd2.js: 195 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application / wasm'.

I don't know which web server you're using, but this is a missing configuration item on the web server - it sends *.wasm files to client as requested, but doesn't mark them with correct MIME type so client is not sure if they're text or binary.

In the dev web server that's included with `face-api`, you can see the example of a correct MIME configuration:
`server/serve.js`
```js
const mime = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpg',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.svg': 'image/svg+xml',
  '.mp4': 'video/mp4',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.wasm': 'application/wasm',
};
```

btw, not related to this issue at all, but you might want to add check if video is buffering data by adding `this.video.readyState > 2` to avoid runtime some errors that can happen

**Comment by deylyn** [comment]
the server is apache

**Comment by vladmandic** [comment]
In that case you can do it in several ways:
- Apache's global MIME configuration in `mime.types`
- Apache's per-folder MIME configuration in `.htaccess`
- Using Apache extension that handles MIME, for example `mod_mime`

Check Apache docs (or just Google) for exact syntax - I don't use Apache for a while now.
