### ISSUE TITLE
Can't get result from some url

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/face-api#52]
When i try, this url it works and can detect

baseImg = https://cdn.etohum.com//3415.jpg?width=300&height=300&crop=true&type=jpeg&top=true

But with below, i cant get result probably because of RGBA image, we experienced this in human side thanks to you it is solved, face and human data types are different so i guess i need a healthy way to convert image for faceapi this time;

img = https://firebasestorage.googleapis.com/v0/b/zetform-63ea7.appspot.com/o/organizations%2FuQbMQXCc2tOqjcG4NpEz%2Fmonitorings%2FRvNxY92jwm7FmqjjBSIA%2Ftestinstances%2FykCFB5VobSyqVXkygDOs%2Fphotos%2F3_2021-04-20%2017%3A55%3A25.jpg?alt=media&token=9e4045f3-7132-4b55-8182-ccc35cb406e2

main function 

```
  const baseFaceTensor = await urlImageFace(baseImageUrl);
    console.log(`Base image url : ${baseImageUrl}`);
    let baseImageDetection = await FACE_API.detectSingleFace(baseFaceTensor);
    console.log(baseFaceTensor);
    console.log(`Base image result : ${JSON.stringify(baseImageDetection)}`);

    const faceTensor = await urlImageFace(imageUrl);
    console.log(`Image url : ${imageUrl}`);
    let imageDetection = await FACE_API.detectSingleFace(faceTensor);
    console.log(`Image result : ${JSON.stringify(imageDetection)}`);
```

converter function

`async function urlImageFace(url: string): Promise<Canvas> {
  const img = await canvas.loadImage(url);
  const c: Canvas = canvas.createCanvas(img.width, img.height);
  const ctx = c.getContext('2d');
  ctx.drawImage(img, 0, 0, img.width, img.height);
  return c;
}`

img result is **undefined**

baseImg result ;

`{"detection":{"_imageDims":{"_width":300,"_height":300},"_score":0.9976093769073486,"_classScore":0.9976093769073486,"_className":"","_box":{"_x":124.07849729061127,"_y":58.481401205062866,"_width":54.043176770210266,"_height":68.65620017051697}},"landmarks":{"_imgDims":{"_width":54,"_height":68},"_shift":{"_x":124.07849729061127,"_y":58.481401205062866},"_positions":[{"_x":120.85518828034401,"_y":81.02721881866455},{"_x":120.71701441705227,"_y":88.84860563278198},{"_x":120.98090274631977,"_y":96.0622034072876},{"_x":121.51622291654348,"_y":102.37310743331909},{"_x":122.78241972997785,"_y":109.49110436439514},{"_x":125.95677074790001,"_y":115.32119131088257},{"_x":130.28979291021824,"_y":119.44327092170715},{"_x":136.257010191679,"_y":124.08218765258789},{"_x":145.44469159841537,"_y":127.46338200569153},{"_x":155.15684974193573,"_y":126.09272766113281},{"_x":161.93911027908325,"_y":123.1921558380127},{"_x":167.1705765724182,"_y":120.24840211868286},{"_x":171.88425850868225,"_y":115.14139103889465},{"_x":175.22645723819733,"_y":108.75134587287903},{"_x":177.0073914527893,"_y":102.24288082122803},{"_x":178.92500245571136,"_y":95.49140310287476},{"_x":179.8350180387497,"_y":88.06687307357788},{"_x":127.940269947052,"_y":75.45436489582062},{"_x":131.76312348246574,"_y":73.33397936820984},{"_x":136.0147544145584,"_y":73.12188285589218},{"_x":139.93764925003052,"_y":73.84130990505219},{"_x":143.3716133236885,"_y":75.51655995845795},{"_x":158.46489536762238,"_y":77.16854918003082},{"_x":162.0581327676773,"_y":76.36341595649719},{"_x":166.23921489715576,"_y":76.35853803157806},{"_x":170.78442299365997,"_y":77.56704139709473},{"_x":173.98983550071716,"_y":80.27199971675873},{"_x":149.7866354584694,"_y":85.10771954059601},{"_x":149.1838851571083,"_y":90.43016183376312},{"_x":148.42311841249466,"_y":95.14306616783142},{"_x":147.69247180223465,"_y":99.32246899604797},{"_x":142.78614234924316,"_y":100.2460241317749},{"_x":144.79968523979187,"_y":101.60989356040955},{"_x":147.67254835367203,"_y":102.40084290504456},{"_x":150.8202343583107,"_y":102.04974579811096},{"_x":153.16719889640808,"_y":101.63336110115051},{"_x":132.85474580526352,"_y":81.75076687335968},{"_x":135.57794165611267,"_y":81.2574702501297},{"_x":139.20949870347977,"_y":81.60047125816345},{"_x":142.37340027093887,"_y":83.65502202510834},{"_x":139.38527888059616,"_y":84.35140407085419},{"_x":135.51377302408218,"_y":83.66151916980743},{"_x":157.91564548015594,"_y":85.28257095813751},{"_x":161.4507862329483,"_y":84.01510286331177},{"_x":165.25217378139496,"_y":84.35735607147217},{"_x":167.62154495716095,"_y":85.82754683494568},{"_x":164.6939502954483,"_y":87.08810234069824},{"_x":160.8412960767746,"_y":86.4825668334961},{"_x":134.39271372556686,"_y":106.06995034217834},{"_x":138.76355463266373,"_y":105.34680151939392},{"_x":144.6028035879135,"_y":105.35100865364075},{"_x":147.4310240149498,"_y":106.07166075706482},{"_x":149.98530024290085,"_y":105.82894802093506},{"_x":156.2930817604065,"_y":107.24864101409912},{"_x":160.88993632793427,"_y":108.75533413887024},{"_x":155.0191719532013,"_y":112.29439330101013},{"_x":150.7055457830429,"_y":113.77883076667786},{"_x":146.32683044672012,"_y":113.92894196510315},{"_x":142.47318810224533,"_y":113.0419499874115},{"_x":138.50945180654526,"_y":110.89265561103821},{"_x":134.87744334340096,"_y":106.21800255775452},{"_x":142.9297295808792,"_y":107.0421793460846},{"_x":147.11835139989853,"_y":107.6575436592102},{"_x":151.34333431720734,"_y":108.0135247707367},{"_x":159.98774528503418,"_y":108.62691926956177},{"_x":150.7983877658844,"_y":110.58375144004822},{"_x":146.81495493650436,"_y":110.74887943267822},{"_x":142.94862306118011,"_y":110.17836689949036}]},"unshiftedLandmarks":{"_imgDims":{"_width":54,"_height":68},"_shift":{"_x":0,"_y":0},"_positions":[{"_x":-3.2233090102672577,"_y":22.545817613601685},{"_x":-3.361482873558998,"_y":30.367204427719116},{"_x":-3.0975945442914963,"_y":37.58080220222473},{"_x":-2.5622743740677834,"_y":43.891706228256226},{"_x":-1.296077560633421,"_y":51.009703159332275},{"_x":1.878273457288742,"_y":56.8397901058197},{"_x":6.211295619606972,"_y":60.96186971664429},{"_x":12.178512901067734,"_y":65.60078644752502},{"_x":21.366194307804108,"_y":68.98198080062866},{"_x":31.078352451324463,"_y":67.61132645606995},{"_x":37.860612988471985,"_y":64.71075463294983},{"_x":43.092079281806946,"_y":61.767000913619995},{"_x":47.805761218070984,"_y":56.65998983383179},{"_x":51.14795994758606,"_y":50.26994466781616},{"_x":52.92889416217804,"_y":43.76147961616516},{"_x":54.8465051651001,"_y":37.01000189781189},{"_x":55.75652074813843,"_y":29.585471868515015},{"_x":3.861772656440735,"_y":16.97296369075775},{"_x":7.684626191854477,"_y":14.852578163146973},{"_x":11.936257123947144,"_y":14.640481650829315},{"_x":15.85915195941925,"_y":15.359908699989319},{"_x":19.29311603307724,"_y":17.03515875339508},{"_x":34.38639807701111,"_y":18.687147974967957},{"_x":37.97963547706604,"_y":17.882014751434326},{"_x":42.160717606544495,"_y":17.877136826515198},{"_x":46.705925703048706,"_y":19.08564019203186},{"_x":49.911338210105896,"_y":21.790598511695862},{"_x":25.708138167858124,"_y":26.626318335533142},{"_x":25.10538786649704,"_y":31.948760628700256},{"_x":24.344621121883392,"_y":36.661664962768555},{"_x":23.613974511623383,"_y":40.84106779098511},{"_x":18.707645058631897,"_y":41.764622926712036},{"_x":20.721187949180603,"_y":43.12849235534668},{"_x":23.59405106306076,"_y":43.91944169998169},{"_x":26.741737067699432,"_y":43.568344593048096},{"_x":29.088701605796814,"_y":43.15195989608765},{"_x":8.776248514652252,"_y":23.269365668296814},{"_x":11.499444365501404,"_y":22.776069045066833},{"_x":15.1310014128685,"_y":23.119070053100586},{"_x":18.294902980327606,"_y":25.17362082004547},{"_x":15.306781589984894,"_y":25.87000286579132},{"_x":11.435275733470917,"_y":25.180117964744568},{"_x":33.83714818954468,"_y":26.801169753074646},{"_x":37.372288942337036,"_y":25.5337016582489},{"_x":41.17367649078369,"_y":25.8759548664093},{"_x":43.54304766654968,"_y":27.346145629882812},{"_x":40.615453004837036,"_y":28.606701135635376},{"_x":36.76279878616333,"_y":28.001165628433228},{"_x":10.314216434955597,"_y":47.58854913711548},{"_x":14.68505734205246,"_y":46.865400314331055},{"_x":20.524306297302246,"_y":46.86960744857788},{"_x":23.35252672433853,"_y":47.59025955200195},{"_x":25.90680295228958,"_y":47.34754681587219},{"_x":32.21458446979523,"_y":48.767239809036255},{"_x":36.811439037323,"_y":50.27393293380737},{"_x":30.940674662590027,"_y":53.812992095947266},{"_x":26.62704849243164,"_y":55.29742956161499},{"_x":22.248333156108856,"_y":55.44754076004028},{"_x":18.394690811634064,"_y":54.56054878234863},{"_x":14.43095451593399,"_y":52.41125440597534},{"_x":10.798946052789688,"_y":47.73660135269165},{"_x":18.851232290267944,"_y":48.56077814102173},{"_x":23.039854109287262,"_y":49.17614245414734},{"_x":27.26483702659607,"_y":49.53212356567383},{"_x":35.90924799442291,"_y":50.1455180644989},{"_x":26.719890475273132,"_y":52.10235023498535},{"_x":22.736457645893097,"_y":52.267478227615356},{"_x":18.870125770568848,"_y":51.69696569442749}]},"alignedRect":{"_imageDims":{"_width":300,"_height":300},"_score":0.9976093769073486,"_classScore":0.9976093769073486,"_className":"","_box":{"_x":114.80521405488253,"_y":67.68773294091226,"_width":70.94160434603693,"_height":65.20979897975921}},"angle":{"roll":-0.11672766465663492,"pitch":0.07139194507918284,"yaw":-0.33357952252539474},"expressions":{"neutral":3.8578268357625234e-10,"happy":1,"sad":1.5390822297178808e-12,"angry":3.267717346711052e-11,"fearful":1.6766032938614166e-14,"disgusted":7.074605345991358e-9,"surprised":2.202393432557126e-12},"descriptor":{"0":-0.1349954903125763,"1":-0.00383098516613245,"2":0.026064850389957428,"3":-0.06253636628389359,"4":-0.07294207811355591,"5":-0.10778254270553589,"6":0.04157354682683945,"7":-0.055339716374874115,"8":0.11064469069242477,"9":-0.001926228404045105,"10":0.12700673937797546,"11":-0.07955881953239441,"12":-0.1769789755344391,"13":-0.012578554451465607,"14":-0.01091816183179617,"15":0.05831509828567505,"16":-0.20441895723342896,"17":-0.10909132659435272,"18":-0.09465648978948593,"19":-0.037060223519802094,"20":0.06026291847229004,"21":-0.023215286433696747,"22":0.025254035368561745,"23":0.0751262903213501,"24":-0.12100088596343994,"25":-0.294894814491272,"26":-0.14616863429546356,"27":-0.007880615070462227,"28":0.05986291915178299,"29":-0.034005340188741684,"30":0.0668824091553688,"31":0.16395270824432373,"32":-0.1730918139219284,"33":-0.11485938727855682,"34":0.0687878206372261,"35":0.1032743901014328,"36":0.005319777876138687,"37":-0.01689540222287178,"38":0.18072715401649475,"39":-0.020627979189157486,"40":-0.13309717178344727,"41":0.05123228579759598,"42":0.050005458295345306,"43":0.36286723613739014,"44":0.14997558295726776,"45":0.1098690778017044,"46":-0.026445843279361725,"47":-0.057895153760910034,"48":0.10304757952690125,"49":-0.28323161602020264,"50":0.06952199339866638,"51":0.19740347564220428,"52":0.048222701996564865,"53":0.031479865312576294,"54":0.0920865386724472,"55":-0.09178395569324493,"56":0.1103983223438263,"57":0.1232658177614212,"58":-0.20526114106178284,"59":0.054151881486177444,"60":0.0885997787117958,"61":-0.03711840882897377,"62":0.08623755723237991,"63":-0.12073357403278351,"64":0.1085720956325531,"65":0.03570355847477913,"66":-0.0881534144282341,"67":-0.09348952770233154,"68":0.05820057541131973,"69":-0.13804568350315094,"70":0.004564085975289345,"71":0.045562125742435455,"72":-0.12411823123693466,"73":-0.19604453444480896,"74":-0.30623453855514526,"75":0.076019287109375,"76":0.43541425466537476,"77":0.1760491132736206,"78":-0.12408383190631866,"79":0.03355195373296738,"80":-0.03132125362753868,"81":-0.03928499296307564,"82":0.1120387464761734,"83":0.00067950040102005,"84":-0.18385279178619385,"85":-0.005263097584247589,"86":-0.13899032771587372,"87":0.06951217353343964,"88":0.15472730994224548,"89":0.02182161808013916,"90":-0.02992740273475647,"91":0.1791854053735733,"92":0.049786705523729324,"93":-0.028928251937031746,"94":0.0649631917476654,"95":0.025132261216640472,"96":-0.10960439592599869,"97":0.02571445144712925,"98":-0.21299579739570618,"99":0.0500495582818985,"100":0.02644030749797821,"101":-0.08359766006469727,"102":0.022061776369810104,"103":0.12894141674041748,"104":-0.1345120668411255,"105":0.12630078196525574,"106":-0.013402394950389862,"107":-0.07819202542304993,"108":-0.10407000780105591,"109":0.0002585873007774353,"110":-0.1769947111606598,"111":-0.0453077033162117,"112":0.11151634156703949,"113":-0.2253071665763855,"114":0.07506467401981354,"115":0.19966936111450195,"116":0.03586537018418312,"117":0.1311870813369751,"118":0.0607939176261425,"119":0.06628672033548355,"120":-0.04801439493894577,"121":0.05651909112930298,"122":-0.05420826002955437,"123":-0.025805585086345673,"124":0.1171688660979271,"125":0.027032427489757538,"126":0.06286288052797318,"127":0.007505020126700401}}`

**Comment by vladmandic** [comment]
Lets see that image without even looking at `FaceAPI`:

```log
curl "https://firebasestorage.googleapis.com/v0/b/zetform-63ea7.appspot.com/o/organizations%2FuQbMQXCc2tOqjcG4NpEz%2Fmonitorings%2FRvNxY92jwm7FmqjjBSIA%2Ftestinstances%2FykCFB5VobSyqVXkygDOs%2Fphotos%2F3_2021-04-20%2017%3A55%3A25.jpg?alt=media&token=9e4045f3-7132-4b55-8182-ccc35cb406e2" >test.jpg
```

Image gets downloaded (104KB), but when I open it, it doesn't contain actual face - it's just very dark noise!
And it's same if I download it using Chrome.

This is the image when I increase brightness to maximum:

![image](https://user-images.githubusercontent.com/57876960/115996440-4924b600-a5ad-11eb-8c65-0068af07fb87.png)

**Comment by okeoke85** [comment]
So sorry after too many attempts i confused myself, by the way is this function sufficient for conversion;

async function urlImageFace(url: string): Promise<Canvas> { const img = await canvas.loadImage(url); const c: Canvas = canvas.createCanvas(img.width, img.height); const ctx = c.getContext('2d'); ctx.drawImage(img, 0, 0, img.width, img.height); return c; }

**Comment by vladmandic** [comment]
yes, that's sufficient  

you can use resulting canvas and pass it to either `human` or `faceapi` and it will work  
or you can convert to tensor and pass it to either libraries  
(libraries internally convert any known input to tensor anyhow, if you pass tensor it bypasses processing within a library as tensor is used as-is)  
or use fetch & decode using tfjs to avoid dependency on `canvas`  

all of the above are fine

**Comment by okeoke85** [comment]
thanks again as always
