### ISSUE TITLE
How to save to file and restore from file labeledDescriptors?

### ISSUE THREAD

**Issue by layanto** [vladmandic/face-api#53]
For nodejs, after generating labeledDescriptors from training photos, how can I save it to file and restore from file on next execution so not to have to re-generate the descriptors from training photos?

**Comment by vladmandic** [comment]
there are tons of way of doing this, but here's one:

once you have `labeledDescriptors`
1. invoke it's `const json = labeledDescriptors.toJSON()` method to get simple object
2. convert object to string by using `const text = JSON.stringify(json)`
3. write text to file using `fs.writeFileSync('mydata.json', text);

and when you want to use it later, just do the opposite:
1. load from file `fs.readFileSync`
2. convert text to object `JSON.parse`
3. load back into `labeledDescriptors` using `fromJSON` method

i'll close the this issue as it's not really an issue, but you can keep the conversation going.

**Comment by layanto** [comment]
Thanks. Didn't know labeledDescriptors has toJSON and fromJSON methods.

**Comment by t-bello7** [comment]
@vladmandic can you explain further how to loadback into labeledDescriptors using fromJSON method

**Comment by zavalyshyn** [comment]
Just for others coming here later on:
In the latest face-api API you need to call toJSON() and fromJSON() function on `faceapi.FaceMatcher` class.
Like so,

```js
  // train the model on a set of faces & save to json file (uncomment when needed)
  const labeledFaceDescriptors = await loadLabeledImages();
  const faceMatcher = new faceapi.FaceMatcher(labeledFaceDescriptors)
  const jsonFM = faceMatcher.toJSON();
  const stringFM = JSON.stringify(jsonFM);
  fs.writeFileSync('trainedfacematcher.json',stringFM);

  // load pretrained face model
  const faceMatcherString = fs.readFileSync('trainedfacematcher.json');
  const faceMatcherJSON = JSON.parse(faceMatcherString);
  const faceMatcher2 = faceapi.FaceMatcher.fromJSON(faceMatcherJSON)
```
