### ISSUE TITLE
Protection against image fraud

### ISSUE THREAD

**Issue by shurshilov** [vladmandic/face-api#59]
Any idea how Recognizing real people is not a problem, I know it's possible. But is it implemented here, I myself have been using the original project for 2 years
Thank you

**Comment by vladmandic** [comment]
real vs fake image detection? no, it's not implemented here.  
i actually wrote a quick test model last month that does that - <https://github.com/vladmandic/anti-spoofing>

closing the issue as it will not be added to `face-api`

**Comment by shurshilov** [comment]
> real vs fake image detection? no, it's not implemented here.
> i actually wrote a quick test model last month that does that - https://github.com/vladmandic/anti-spoofing
> 
> closing the issue as it will not be added to `face-api`

Its my module
https://apps.odoo.com/apps/modules/14.0/hr_attendance_face_recognition/
This is my paid module, I can take you as a co-author or pay and you will be able to develop your project with income. 
The main function that I would like to modify is the difference from the image. I saw that you have made the implementation of rolls and so on it seems to me that you can use these parameters for protection)

**Comment by shurshilov** [comment]
go to whatsapp +79857972124 or telegram @eurodoo
