### ISSUE TITLE
Using FaceAPI with WASM in next.js (client side only)

### ISSUE THREAD

**Issue by felipenmoura** [vladmandic/face-api#65]
**Issue Description**
When trying to dynamically import dependencies to use wasm, it seems to be ignoring it, still using webgl.  
In Next.js, it's important to only load dependencies in the client-side, avoiding larger bundles and other SSR problems.

**Steps to Reproduce**

```js
React.useEffect(_ => {
        Promise.all([
          import('@tensorflow/tfjs'), // dynamic import
          import('@tensorflow/tfjs-backend-wasm') // dynamic import
        ]).then(async ([tf, wasm]) => {
          window.tf = tf;
          wasm = wasm;
          window.wasm = wasm;
          wasm.setWasmPaths('https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.9.0/dist/');

          await tf.setBackend('wasm');
          await tf.ready();
          console.log(tf.getBackend()); // wasm <<<--- OK

          await createScript('/face-detection-ia/face-api.min.js', scrId); // imports the script from /public

          const faceapi = window.faceapi;

          try {
            await Promise.all([
              faceapi.nets.tinyFaceDetector.loadFromUri('/face-detection-ia/models/'),
              faceapi.nets.faceLandmark68Net.loadFromUri('/face-detection-ia/models/'),
            ]); // this also loads all the models OK
            console.log('DONE loading AI stuff');
            console.log(faceapi.tf.getBackend()); // webgl <<<<<----- !!!!!!!!!
          } catch (error) {
            console.error('ERROR loading AI stuff', error);
            return;
          }
        });
      }
}, []);
```

**Expected Behavior**

After loading the faceapi script, `faceapi.tf.getBackend()` should be `wasm`.

**Environment

- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)?
Chrome and Firefox LTS
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)?
MacOS on a MacBook Pro
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)
Next.js

Issue coming from https://github.com/justadudewhohacks/face-api.js/issues/799

**Comment by felipenmoura** [comment]
Also, if I add `faceapi.tf.setBackend('wasm');` right after creating the script and appending it (waiting for it to load), it triggers another error:

```
Unhandled Runtime Error
Error: Backend name 'wasm' not found in registry
```

Even though tf.getBackend() returns `wasm`.

**Comment by vladmandic** [comment]
> I had to do all that because I'm using next.js and its SSR insists on trying to render it in the backend,
> requiring many other dependencies...I'm trying to avoid that by ensuring it ONLY runs on client side.

you need to tell next.js not to mess with dependencies  
(this is still recommended for `next.js` so its `webpack` does not mess things up regardless of everything else)  

for example, this is next.config.js i've tested a while back:

module.exports = {
  webpack: (config) => {
    if (config.target === 'web') config.externals = [ 'fs', 'os', 'util' ];
    return config;
  },
}

loading WASM modules via next.js is tricky at best.
if you want to dynamically import wasm and not have SSR, i don't see where is that set?

in the past i've done something like this:  
(again, still recommedned to do dynamic imports and specify ssr false)  

const wasm = dynamic(
  () => import('@tensorflow/tfjs-backend-wasm'),
  { ssr: false }
)
and that should be in the component init, not calling faceapi immediately afterwards  
(this is pretty important - how would you then use faceapi for the second time? load modules again?)

> Error: Backend name 'wasm' not found in registry

first, you're loading faceapi via:

```js
  await createScript('/face-detection-ia/face-api.min.js', scrId); // imports the script from /public
```

that looks like IIFE version of `FaceAPI` while on top you're using TF ESM modules  
(ok, this is not critical, but troubleshooting mixing ESM and IIFE is nearly impossible)  
plus IIFE is ooold. why not load `FaceAPI` the same way you load TF on top? plus use ESM version  

what is critical is that you're loading `FaceAPI` **after** loading `tfjs-backend-wasm`  
well, `tfjs-backend-wasm` will try to register itself with a valid TFJS instance, but only one loaded at that time is the one you've loaded.
but `FaceAPI` IIFE version has an embedded version of TFJS so you're basically loading it twice and registration gets messed up.

mandatory:
- separate module loader from actual detection
- switch to using FaceAPI ESM version
- load it on top before tfjs-backend-wasm
- don't load `tfjs` explicitly, it's not needed
- second `tfjs-backend-wasm` last

recommended:
- add dynamic/ssr:false flags to improrts
- add Next config on server-side to avoid webpack messing things up

**Comment by vladmandic** [comment]
@felipenmoura any updates?

**Comment by vladmandic** [comment]
closing issue due to idle time, will reopen if additional information is provided.
