### ISSUE TITLE
How does detectAllFaces function will handle fake image photo by mobile

### ISSUE THREAD

**Issue by danies8** [vladmandic/face-api#68]
Hi,
I used this code that  detect all faces, I want to avoid that user will photo himself by cellular and show the cellular photo to camera  , how I avoid by code ?
For know fake image by cellular also work.
I saw this link in history issue and there is no option do install through npm ?
https://github.com/vladmandic/anti-spoofing

```
 const ssdOptions = { minConfidence: 0.1, maxResults: 10 };
      const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);
      const faces = await faceapi
        .detectAllFaces(tensor, optionsSSDMobileNet)
        .withFaceLandmarks()
        .withFaceExpressions()
        .withFaceDescriptors()
        .withAgeAndGender();

```

**Comment by vladmandic** [comment]
faceapi does not perform any analysis on the detected face - real or fake or doctored or anything  
and given that faceapi here is strictly in maintenance mode, this request is out of scope

**Comment by danies8** [comment]
Thanks a lot:)
I tested this link and is not solved the problem:
https://github.com/vladmandic/anti-spoofing

**Comment by vladmandic** [comment]
that is just a test - a very simple model and trained on small dataset to detect real people vs fake images. it has nothing to do with photo on the phone.

**Comment by danies8** [comment]
Hi,
Do you know any other lib that will solved this issue,
that I can add to my solution for detecting fake images ?

**Comment by vladmandic** [comment]
i dont, sorry...

**Comment by danies8** [comment]
thanks a lot

**Comment by danies8** [comment]
Hi,
Can you give an example how to do it ?

**Comment by vladmandic** [comment]
> Can you give an example how to do it ?

Example would be to write it all. I may do it, but its not a priority.

> It also good for picture not only phone ?

Looks that way.
