### ISSUE TITLE
Incorrect README statement: `tinyYolov2: Non-functional since weights are missing`

### ISSUE THREAD

**Issue by ndtreviv** [vladmandic/face-api#7]
The tinyYolov2 models are available here: https://github.com/justadudewhohacks/face-api.js-models

**Comment by vladmandic** [comment]
Thanks - They were missing from the original package.
I may re-add it back if there is a demand - seems two remaining models are sufficient - let me know if you need this?

**Comment by ndtreviv** [comment]
I have no specific requirement. It took me a while to find them as well! Not least because the faceDetection.ts example seems to want to reference the TinyYolov2 model out of the box.
