### ISSUE TITLE
withFaceExpressions() && withAgeAndGender() wheather or not to use in detectAllFaces

### ISSUE THREAD

**Issue by danies8** [vladmandic/face-api#71]
Hi,
I have two actions `register `and `compare`, I would like to ask if
to use withFaceExpressions() && withAgeAndGender() or not ?
When I will use them ?
Thanks in advance.
     ```
const ssdOptions = { minConfidence: 0.1, maxResults: 10 };
      const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);
      const faces = await faceapi
        .detectAllFaces(tensor, optionsSSDMobileNet)
        .withFaceLandmarks()
        .withFaceExpressions()
        .withFaceDescriptors()
        .withAgeAndGender();
```

**Comment by vladmandic** [comment]
`withFaceExpressions` predicts facial expressions (e.g. emotions)  
`withAgeAndGender` predicts age and gender  
neither of those have anything to do with face descriptors or face recognition  
so if you don't use those results, don't load those models and don't invoke those methods
