### ISSUE TITLE
Migration @vladmandic/face-api to old face-api 

### ISSUE THREAD

**Issue by danies8** [vladmandic/face-api#79]
Hi,
What are steps that need to be done ?
1.pacakge json for  @vladmandic/face-api we used:
 "@tensorflow/tfjs-node": "^3.9.0",
    "@vladmandic/face-api": "^1.5.4",
what are in old face-api ?
2.The project old face-api written in typescript, can I used it in js ?
3.What about modal they can be loaded in startup like in @vladmandic/face-api ?
4.const faceapi = require('@vladmandic/face-api'); in old api how is it  in js?
5.Does the interface(methods of faceapi are same on both platform ?
Thanks,

**Comment by vladmandic** [comment]
Read paragraph in README: <https://github.com/vladmandic/face-api#differences>

1. Original `face-api` is based on `tfjs` 1.7.6 and not compatible with `tfjs` 2.x or 3.x
2. Incorrect - both are written in TS and compiled to JS. What you're using is JS module.
  Original `face-api` is written in TypeScript v3 and compiled to JS ES2015, new is in TypeScript v4 and compiled to JavaScript ES2018
3. Same. Read install notes for old and new
4. Same. Read install notes for old and new
5. 99% are same, face angle calculations are new.

**Comment by danies8** [comment]
I used :
 "@tensorflow/tfjs-node": "1.0.2",
    "@tensorflow/tfjs-core": "1.0.3",
    "face-api.js": "^0.22.2",
and when run the app I got:
Error: The specified module could not be found.
\\?\D:\FC TEMP\Face Recognition API\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node

**Comment by vladmandic** [comment]
sorry, but if youre using old `face-api`, that's not my problem and i'm not going to troubleshoot issues with `tfjs` v1 - that is why i created new `face-api`!

**Comment by danies8** [comment]
I do it only for comparison :)

**Comment by vladmandic** [comment]
i understand, but its a nightmare top get old `tfjs` to work with new `nodejs`. if you want to test old `face-api`, you need `tfjs` 1.7 (not 1.0) and `nodejs` 12.

**Comment by danies8** [comment]
I used 
![image](https://user-images.githubusercontent.com/1079689/140652268-cd8de0e3-7fd5-4e97-8a92-0fab8be9ba9e.png)
 but got error node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node module not found

**Comment by vladmandic** [comment]
that means that `tfjs-node` post-install didn't manage to create wrapper for `tensorflow.so` shared library. clean everything (definitely clean any modules cache), try again. do note that this is not `face-api` related at all, its about getting old `tfjs-node` installed.

**Comment by danies8** [comment]
I removed the node modules and got the The specified module could not be found:
node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node

**Comment by vladmandic** [comment]
I just tried using `nodejs` 12.20.0 and `tfjs-node` 1.7.4 and it works on my system without errors - don't know why your installation of `tfjs-node` fails.

**Comment by danies8** [comment]
I used: this tfjs-node and it works your get same error.
"@tensorflow/tfjs-node": "**1.0.2**", 
    "face-api.js": "0.20.0",

**Comment by vladmandic** [comment]
face-api 0.22 is only one i've ever tried and it explicitly requires tfjs 1.7

**Comment by danies8** [comment]
When I used face-api 0.22 && tfjs 1.7 installtion passed OK.
But when I loadeed the app i got the error:
The specified module could not be found:
node_modules@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node

**Comment by vladmandic** [comment]
I just created a test project and it works!

```json
{
  "name": "faceapi.022",
  "main": "faceapi-022.js",
  "scripts": {},
  "dependencies": {
    "@canvas/image": "^1.0.1",
    "@tensorflow/tfjs-node": "1.7.4",
    "face-api.js": "^0.22.2"
  }
}
```

```js
const fs = require('fs');
const tf = require('@tensorflow/tfjs-node');
const image = require('@canvas/image');
const faceapi = require('face-api.js');

const modelPath = 'weights/';
const imageFile = 'sample.jpg';
const ssdOptions = { minConfidence: 0.1, maxResults: 10 };

async function main() {
  const buffer = fs.readFileSync(imageFile);
  const canvas = await image.imageFromBuffer(buffer);
  const imageData = image.getImageData(canvas);
  const tensor = tf.tidy(() => {
    const data = tf.tensor(Array.from(imageData?.data || []), [canvas.height, canvas.width, 4], 'int32');
    const channels = tf.split(data, 4, 2);
    const rgb = tf.stack([channels[0], channels[1], channels[2]], 2);
    const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]);
    return reshape;
  });
  await faceapi.nets.ssdMobilenetv1.loadFromDisk(modelPath);
  await faceapi.nets.ageGenderNet.loadFromDisk(modelPath);
  await faceapi.nets.faceLandmark68Net.loadFromDisk(modelPath);
  await faceapi.nets.faceRecognitionNet.loadFromDisk(modelPath);
  await faceapi.nets.faceExpressionNet.loadFromDisk(modelPath);
  const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);
  const result = await faceapi
    .detectAllFaces(tensor, optionsSSDMobileNet)
    .withFaceLandmarks()
    .withFaceExpressions()
    .withFaceDescriptors()
    .withAgeAndGender();
  console.log('results:', result);
  console.log('backend', tf.getBackend());
}

main();
```

**Comment by danies8** [comment]
After installtion and the run the app i got:
return process.dlopen(module, path._makeLong(filename));

**Comment by danies8** [comment]
I called this function without success? why ?

const tf = require('@tensorflow/tfjs-node');
const faceapi = require('face-api.js');
const path = require('path');

async function loadModals() {
      const modelPath = '../../weights';
      const faceDetectionNet = new faceapi.FaceDetectionNet();
      await faceDetectionNet.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.ssdMobilenetv1.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceLandmark68Net.loadFromDisk(path.join(__dirname, modelPath));
      await faceapi.nets.faceRecognitionNet.loadFromDisk(path.join(__dirname, modelPath));
}
module.exports = { loadModals }

**Comment by vladmandic** [comment]
no idea :(

**Comment by danies8** [comment]
Which node did you use ?

**Comment by vladmandic** [comment]
NodeJs v14 for this test

**Comment by danies8** [comment]
I have  v12.18.2 it will be working ?

**Comment by vladmandic** [comment]
for original faceapi, *yes*  
for my new one, *no*. there is no technical reason, but i've set minimum required version to nodejs 14 as nodejs 12 is *EOL**  
(note that nodejs 16 is current stable and 17 is what i use for development)

**Comment by danies8** [comment]
Installtion is ok(npm installed)
but whem I run the app I got this error:
![image](https://user-images.githubusercontent.com/1079689/142217292-bfbe8925-ee62-4fe5-a66d-3c9b62da089b.png)

**Comment by danies8** [comment]
Pacake json:
 "dependencies": {
    "@canvas/image": "^1.0.1",
    "@tensorflow/tfjs-node": "1.7.4",
     "assert": "^2.0.0",
    "atob": "^2.1.2",
    "base64-img": "^1.0.4",
    "body-parser": "^1.19.0",
    "canvas": "^2.8.0",
    "compression": "^1.7.4",
    "cors": "^2.8.5",
    "crypto": "^1.0.1",
    "dotenv": "^10.0.0",
    "ejs": "^3.1.6",
    "enum": "^3.0.4",
    "express": "^4.17.1",
    "express-ejs-layouts": "^2.5.1",
    "express-winston": "^4.2.0",
    "face-api.js": "0.22.2",
    "mssql": "^7.2.1",
    "node-cache": "^5.1.2",
    "node-pre-gyp": "^0.17.0",
    "nodemon": "^2.0.14",
    "performance-now": "^2.1.0",
    "windows-network-drive": "^3.0.1",
    "winston": "^3.3.3"
  }

**Comment by vladmandic** [comment]
`process.dlopen` is defined by `nodejs` itself and its used to load shared library (in this case, `tfjs-node` is loading `tensorflow.dll`)  
<https://nodejs.org/docs/latest-v12.x/api/process.html#process_process_dlopen_module_filename_flags>  

to me, this looks like a broken `nodejs` installation that for unknown reason doesnt support some functions  
really, try to do a clean installation of `nodejs` 14 or 16 (yes, 12 should work, but 12 is end-of-life)

**Comment by vladmandic** [comment]
`process.dlopen` is function provided by `nodejs` and used by `tfjs-node`to load shared library defined in `tfjs-binding.node` which basically points to `tensorflow.dll`  

and in your case, that is broken - even if `tfjs-node` looks like its installed correctly, it is not - that file is created during post-install and in your case, its not working  

really, nodejs 12 is end-of-line - try clean install nodejs 14 or 16 and then install `tfjs-node`

**Comment by danies8** [comment]
I installed node 16.3, removed mode_modules and insalled pacake json and got same error.

**Comment by vladmandic** [comment]
try tfjs 2.8.6 (tfjs 3.x installer on windows is pretty broken)?

> npm install --verbose --force @tensorflow/tfjs-node@2.8.6

**Comment by danies8** [comment]
I remove node modules and installed "@tensorflow/tfjs-node": "2.8.6"  and got same error

**Comment by danies8** [comment]
I tried also npm install --verbose --force @tensorflow/tfjs-node@2.8.6 same error

**Comment by vladmandic** [comment]
node idea why `tfjs-node` is not working on your system. you can try with `--build-from-sources`, but thats pretty painful.  
i cant do much more here, sorry.

**Comment by danies8** [comment]
LIke that:install --verbose --force --build-from-source @tensorflow/tfjs-node@2.8.6

**Comment by vladmandic** [comment]
i think so, cannot test right now. better search on tfjs github.

**Comment by danies8** [comment]
I used node:12.8.2, @tensorflow/tfjs-node 1.0.2,face-api.js 0.20.0 from link:https://github.com/justadudewhohacks/face-api.js/issues/312 and it run but I have problem, while running this code see *:
 ```
 const ssdOptions = { minConfidence: parseFloat(config.ssdOptionsMinConfidence), maxResults: parseInt(config.ssdOptionsMaxResults) };
      const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);
     * const faces = await faceapi
        .detectAllFaces(tensor, optionsSSDMobileNet)
        .withFaceLandmarks()
        .withFaceDescriptors();

        ts.dispose(tensor);
```
get this error:
![image](https://user-images.githubusercontent.com/1079689/142417898-a57ef53b-a43f-4e5b-8c57-979893726f05.png)

**Comment by vladmandic** [comment]
that error indicates that tfjs backend is not initialized.
try doing it explicitly before instantiating face-api

```js
tf.setBackend('tensorflow'); // `tensorflow` is backend provided by `tfjs-node`
await tf.ready();
console.log(tf.getBackend());
```

**Comment by danies8** [comment]
failed:TypeError: tf.ready is not a function

**Comment by vladmandic** [comment]
i never used such an old tfjs :(
i still dont understand why are you going through sooo much trouble to get something obsolete working?

**Comment by danies8** [comment]
I used now tfs 2.8.6 and got this error:
![image](https://user-images.githubusercontent.com/1079689/142422828-5306a15e-d882-4fad-85eb-b5faabd52e6e.png)

**Comment by vladmandic** [comment]
class `faceRecognitionController` does not even exist anymore, so what version of `face-api` is that?  
**always** provide version info for both, i cannot follow your experiments in real-time  
and include backend in use - output of `console.log(tf.getBackend())` - i cannot be guessing that  
and please don't post screenshots of logs, makes it that much more difficult to work with

**Comment by danies8** [comment]
"face-api.js": "0.20.0",

**Comment by vladmandic** [comment]
so it seems that `tfjs-node` is finally working?!
now stop using face-api other than last possible version. i have no idea what 0.20.0 does internally. why try? and if you do, please do not even tell me.

**Comment by danies8** [comment]
I change to last version "face-api.js": "0.22.2" +  tfs 2.8.6  and get the error above :
Error: 'fill' not yet implemented or not found in the registry. This kernel may not be supported by the tfjs backend you have chosen

**Comment by vladmandic** [comment]
`fill` is definitely implemented in `tfjs-node` which tells me that your `tfjs-node` is probably cached 1.0, not `2.8.6` like you say  
what is the output of `console.log(tf.version)`?

**Comment by danies8** [comment]
tensorflow
{
  'tfjs-core': '2.8.6',
  'tfjs-backend-cpu': '2.8.6',
  'tfjs-backend-webgl': '2.8.6',
  'tfjs-data': '2.8.6',
  'tfjs-layers': '2.8.6',
  'tfjs-converter': '2.8.6',
  tfjs: '2.8.6',
  'tfjs-node': '2.8.6'
}

**Comment by danies8** [comment]
I removed nodemodules and install it again and get same error.

**Comment by vladmandic** [comment]
...and we're likely back to square one - old `face-api` is build using `tfjs` **1.7.6** and using any other version causes problems.

**Comment by danies8** [comment]
Yes

**Comment by danies8** [comment]
No matching version found for @tensorflow/tfjs-node@1.7.6

**Comment by vladmandic** [comment]
find a highest version from 1.7.x branch.

**Comment by danies8** [comment]
![image](https://user-images.githubusercontent.com/1079689/142431445-576df2d1-94d8-41f2-bdfb-06f28502f9e1.png)
+ "face-api.js": "0.22.2",

**Comment by vladmandic** [comment]
`face-api` internally packages tfjs-core `1.7.0` which includes cpu backend for math operations.
when you install and load `tfjs-node`, it registers same math operations so when `face-api` is loaded after (must be after), it will use them. but thats why version of `tfjs-node` must be same as version of `tfjs-core` inside `face-api` (its ok to use different patch number, but must be same major version)

**Comment by danies8** [comment]
When installing  tfjs-core 1.7.0 + "face-api.js": "0.22.2",
ger error again:return process.dlopen(module, path.toNamespacedPath(filename));

**Comment by vladmandic** [comment]
read what i said - `tfjs-core` is already EMBEDDED inside `face-api`, its totally pointless to install it.
you need to install `tfjs-node` which matches that version of `tfjs-core` used by `face-api`

**Comment by danies8** [comment]
Sorry I installed tfjs-node1.7.0 + "face-api.js": "0.22.2",
ger error again:return process.dlopen(module, path.toNamespacedPath(filename));

**Comment by danies8** [comment]
v12.18.2.

**Comment by vladmandic** [comment]
back to broken `tfjs-node`. really, why are we discussing this for days? why are you so adamant to get old face-api to work?
i understand you're curios, but this is becoming pointless.

so, back to my comment from 11 days ago:

> sorry, but if youre using old face-api, that's not my problem and i'm not going to troubleshoot issues with old tfjs - that is why i created new face-api!

if you want to continue to try to get old face-api to work, you can post an isuse under original repository.

**Comment by danies8** [comment]
I don't understands why the code not working .why is broken is connected to my computer ?
