### ISSUE TITLE
Unknown dtype undefined

### ISSUE THREAD

**Issue by pabloegpf1** [vladmandic/face-api#8]
Hello!

I recently moved from the original face-api.js library to @vladmandic/face-api because I need to use WASM backend in my face recognition application.

The models are working great in `webgl` and `cpu` backends, but when I switch to `wasm`, the following error shows up:

`Error: Unknown dtype undefined`

I wonder if I have not configured face-api correctly or it is a problem with tfjs with the models.

The source code for the face-api implementation is here: https://github.com/pabloegpf1/Face-App/blob/master/src/scripts/faceApi.js
You can check out the application here: https://www.pabloescriva.com/Face-App/?backend=wasm

**Comment by vladmandic** [comment]
i took a look at your example and error trace in the console is not really helpful  
seems actual error thrown by `tfjs` is a bit earlier:  
```throw new Error(`In local storage, the binary weight values of model '${this.modelPath}' are missing.`);```

but again, that could be misleading due to incomplete trace  

my best guess is that `wasm` initialization is not complete so loading of weights fails  
why? could be due to mismatch of `tfjs` instances.

```js
import {setWasmPaths} from '@tensorflow/tfjs-backend-wasm';
import * as faceapi from '@vladmandic/face-api/dist/face-api.esm';

const MODEL_PATH = './models/'
const WASM_PATH = './wasm/'
const maxDescriptorDistance = 0.6; 
const displayWidth = 750;

export async function loadTensorFlow(backend = "webgl"){
    await setWasmPaths(WASM_PATH);
    await faceapi.tf.setBackend(backend);
    await faceapi.tf.ready();
    console.log(faceapi.tf.version)
    return faceapi.tf;
}
```
you're using `faceapi.tf` which is instance of `tfjs` included in `faceapi`, but `tfjs-backend-wasm` is imported to root.
i'll try to clone your repository and try out few things a bit later, but you might try to import entire `tfjs` yourself and then register it with  `faceapi` - something like:

```js
import * as tf from `@tensorflow/tfjs`
import {setWasmPaths} from '@tensorflow/tfjs-backend-wasm';
import * as faceapi from '@vladmandic/face-api/dist/face-api.nobundle';
faceapi.tf = tf;
```

**Comment by vladmandic** [comment]
i've forked your app to run some debugging...

this it happens only when using `.withFaceLandmarks()` and only with `wasm` backend  

but when you do use it, `face-api` extensively uses `tfjs` function `tf.fill`:

from tfjs sources:

```js
Fill.ts: function fill(args: {attrs: FillAttrs, backend: BackendWasm}) {
  const {attrs: {shape, value, dtype}, backend} = args;
  const out = backend.makeOutput(shape, dtype);
  const outVals = backend.typedArrayFromHeap(out);
  outVals.fill(value as number);
  return out;
}
```

that further calls `wasm` backend function:

```js
backend_wasm.ts: typedArrayFromHeap({shape, dtype, dataId}: TensorInfo): backend_util.TypedArray {
    const buffer = this.wasm.HEAPU8.buffer;
    const {memoryOffset} = this.dataIdMap.get(dataId);
    const size = util.sizeFromShape(shape);
    switch (dtype) {
      case 'float32': return new Float32Array(buffer, memoryOffset, size);
      case 'int32': return new Int32Array(buffer, memoryOffset, size);
      case 'bool': return new Uint8Array(buffer, memoryOffset, size);
      default: throw new Error(`Unknown dtype ${dtype}`);
    }
  }
```

per [tfjs api docs]<https://js.tensorflow.org/api/latest/>, dtype parameter here is optional and should default to `float`  
and that works correctly in `backend-cpu` and `backend-webgl`,  
but *NOT* in `backend-wasm` - you can see that default is just to throw an error!

i suggest to open an issue in `tfjs` to fix this properly, but in the meantime i just did a patch for `face-api` to explicitly set dtype on all `tf.fill` calls and published a new version **0.8.2**

i've tried with your app and it seems that it now works with both `webgl` and `wasm` backends

**Comment by vladmandic** [comment]
@pabloegpf1 can you confirm the fix worked?

**Comment by pabloegpf1** [comment]
@vladmandic the fix works great! thank you so much!! Sorry for the late response.

I am going to start working on a PR to fix this in tfjs during this week

**Comment by vladmandic** [comment]
@pabloegpf1 great - thanks!

**Comment by vladmandic** [comment]
@pabloegpf1 btw, not sure if it would fit your use-case, but i'm mostly done enhancing `face-api` - i've done as much a i can, now it's showing it's age of underlying models.

i've started working on new library, you can check it out if you're interested: <https://github.com/vladmandic/human>

**Comment by pabloegpf1** [comment]
Your new library looks awesome, I am considering moving to Human. Thanks for your hard work!
