### ISSUE TITLE
Create tensor - how I convert it to old face api

### ISSUE THREAD

**Issue by danies8** [vladmandic/face-api#80]
Hi,
  
      let arr = imageStrEncodedBase64.split(',');
      let bstr = atob(arr[1]);
      let n = bstr.length;
      let u8arr = new Uint8Array(n);
      while (n--) {
        u8arr[n] = bstr.charCodeAt(n);
      }
      const tensor = tf.node.decodeImage(u8arr, 3);
   Error:tf.node.decodeImage is not a function
Thanks,

**Comment by vladmandic** [comment]
if you're using old `face-api`, post issues in that forum - i'm not going to troubleshoot something that works in my port of `face-api` and doesnt in the old one.

**Comment by danies8** [comment]
It will be very great if you help how to create tensor in old api js

**Comment by vladmandic** [comment]
its been there for a while :)
<https://github.com/vladmandic/face-api/blob/master/demo/node-image.js>

**Comment by danies8** [comment]
I used your code:
const canvas = await image.imageFromBuffer(Buffer.from(imageStrEncodedBase64.split(',')[1], 'base64')); // decode to canvas
   const imageData = image.getImageData(canvas);

   const tensor = tf.tidy(() => { // create tensor from image data
        *const data = tf.tensor(Array.from(imageData.data || []), [canvas.height, canvas.width, 4], 'int32'); // create rgba image tensor from flat array and flip to height x width
        const channels = tf.split(data, 4, 2); // split rgba to channels
        const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb
        const reshape = tf.reshape(rgb, [1, canvas.height, canvas.width, 3]); // move extra dim from the end of tensor and use it as batch number instead
        return reshape;
      });

Get error in *: TypeError: tfc.ENV.findBackend is not a function

**Comment by vladmandic** [comment]
very weird, but it again points to bad `tfjs-node` installation as it use even basic API.

**Comment by danies8** [comment]
I think I succeded to create tensor:
Create tensor done successfully(tensor shape:1,512,383,3, tensor size:588288
but when I reached to this code i got:
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'backend' of undefined
```
const ssdOptions = { minConfidence: parseFloat(config.ssdOptionsMinConfidence), maxResults: parseInt(config.ssdOptionsMaxResults) };
      const optionsSSDMobileNet = new faceapi.SsdMobilenetv1Options(ssdOptions);
      const faces = await faceapi
        .detectAllFaces(tensor, optionsSSDMobileNet)
        .withFaceLandmarks()
        .withFaceDescriptors();
```

**Comment by vladmandic** [comment]
it means that faceapi is using wrong instance of tf. it has browser version of `tfjs` embedded (even when used in node),  
but that doesnt work in node  

so `const tf = require('@tensorflow/tfjs-node')` should be done *after* `face-api` import so it basically overwrites its internal registrations  

i don't know why are you spending so much time trying old `face-api`? is there a problem with the new one?

**Comment by danies8** [comment]
I used in both places and got same error,

**Comment by vladmandic** [comment]
something is really wrong with installation of `tfjs-node` on your system and i have no idea why...
