### ISSUE TITLE
Face-api with another HTML5 video element

### ISSUE THREAD

**Issue by rexn8r** [vladmandic/face-api#82]
Hi,

I am trying to implement face recognition in an electron app.

Development Device : Jetson Nano 4gb Development kit
Device OS : Ubuntu 18.04 Linux4Tegra, Arm64 architecture
Development Stack : Electron 15.3, Node 16.8, NPM 7.21

App workflow: one window will capture camera feed, detect gender and pass information to another window which will render video based on the gender in html5 video element.

The electron application has main.js which is main process and it launches 2 rendering windows (browserwindow using chromium engine to render html5,css,javascript). 

The inter process communication between 2 windows done via electron ipcRenderer module.

Since the device is Arm64 architecture, i was unable to use @tensorflow/tfjs-node and was getting following error while installing the module;

Unsupported system: cpu-linux-arm64

So i installed following 2 modules;

npm install @tensorflow/tfjs
npm install @vladmandic/face-api

In the camera window i have a script which load following 2 modules;

const tf = require('@tensorflow/tfjs');
const faceapi = require('@vladmandic/face-api/dist/face-api.node-cpu.js');

By default face-api.node-cpu.js was not available in dist folder under @vladmandic/face-api node folder so i copied from github

I was unable to use any other module from @vladmandic/face-api dist folder.

I then followed sample code which captures the webcam and detects faces from live stream.

In another  window, I am playing 4k video in HTML5 video element. 

The problem is, the 4k video drop frames and choppy. But if I stop the camera window, the video plays smooth.

I have tried various chrome switches as well as chromium ffmpeg codec updates but none has worked.

since i am unable to use node modules on arm64, what would be the best approach to develop such application?

Thanks
Rex

**Comment by vladmandic** [comment]
javascript by definition is single-threaded and while `face-api` is performing processing, other tasks will wait - so your video appears choppy. only solution is to run intensive tasks in a separate web worker thread

but here is what i don't understand - you talk about detection in **browser** while using **node-cpu** - which is it? is it nodejs solution or browser solution?

anyhow, `face-api` is not compatible of running in a web worker as it uses DOM elements and rewrite to make it compatible is outside of my scope (library is in maintenance). you may want to check my `human` library which CAN run in web workers.

**Comment by rexn8r** [comment]
Hi vladmandic

thanks for your prompt reply. much appreciate.

I have modified my question above with more details of what i am trying achieve.

any guidance would be appreciated.

thanks
rex

**Comment by vladmandic** [comment]
so (electron or not) detection workflow happens in the browser - in that case, `tfjs-node` is irrelevant, that is only for `nodejs` workflows. and in browser, you can use `tfjs-backend-cpu` (which is included in main `tfjs`) or `tfjs-backend-wasm` or `tfjs-backend-webgl` (which are addons on top of main `tfjs` bundle)

`wasm` is again x86 only, so that wont work. and raspberry pi doesnt have a real gpu, so performance of `webgl` is questionable (but worth a try).

now, if it were me, i'd change the workflow completely - instead of two **browser** windows, i'd change it to main window capturing webcam and extracting `imagedata` from it, send it to **nodejs** process which runs `faceapi` to detect it and send results back to main window so it can do whatever it wants now

why? because there is `tfjs-node` compiled for ARM, it explicitly shipped as part of tfjs-node 3.8.0

**Comment by rexn8r** [comment]
hi vladmandic

thanks for the clarification.
i am using visual studio code and when i execute following npm command:

npm install @tensorflow/tfjs-node

i get error : Unsupported system: cpu-linux-arm64

all the files which are downloaded are automatically removed by the process so if i do following;

npm rebuild @tensorflow/tfjs-node --build-from-source

it doesn't help. i did research but could not find a way to resolve this.

so where do i find tfjs-node package for ARM architecture?

thanks
rex

**Comment by vladmandic** [comment]
i did say `tfjs-node` version 3.8.0 had arm binaries, not every version does:

```text
pi@pi:~/dev $ uname -a
Linux pi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux
pi@pi:~/dev $ npm install @tensorflow/tfjs-node@3.8.0
added 136 packages, and audited 137 packages in 2m
found 0 vulnerabilities
```
