### ISSUE TITLE
Files are not found

### ISSUE THREAD

**Issue by adviner** [vladmandic/face-api#83]
**Issue Description**
When running it gives me several errors:

node_modules/@vladmandic/face-api/types/src/ssdMobilenetv1/SsdMobilenetv1.d.ts(1,21): error TS2307: Cannot find module '../../dist/tfjs.esm' or its corresponding type declarations

Looking at the node_modules it looks like that path are off by one level

File node_modules/@vladmandic/face-api/types/src/ssdMobilenetv1/SsdMobilenetv1.d.ts is going back two levels ../../dist/tfjs.esm but going down "../../" only gets us to the "types" folder not "face-api".  Is there something I'm doing wrong outside of just installing using npm install? 

**Steps to Reproduce**
Part of my project

**Expected Behavior**

**Environment

Docker, node server using following libs:

"@tensorflow/tfjs-node": "^3.11.0",
"@vladmandic/face-api": "^1.5.7",
"canvas": "^2.8.0",

- Module version?
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)?  NodeJS v17.0.1
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Apple silicon running latest docker
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)? none

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
it's not a path issue - error is not really an error as it happens during type checking validation  
currently i do not package typedefs (*.d.ts) for `tfjs`, so you need to have `skipLibCheck=true` in your `tsconfig.json`  
but its a valid request, so i'll keep it open until its implemented  
(basically, i need to generate `tfjs.esm.d.ts` and place it in `types/dist`)

**Comment by adviner** [comment]
I see, thanks for getting back so quickly :)
