### ISSUE TITLE
Cannot find module 'util'

### ISSUE THREAD

**Issue by viis233** [vladmandic/face-api#86]
**Issue Description**
I use the faceapi in the rendering thread of electron. It is normal to run the browser, but the following errors will occur when starting with electron.
How should we solve it ?
thx

![图片](https://user-images.githubusercontent.com/41282272/144189266-f549a25b-9d2d-4cc9-9554-b77548ab481e.png)
![图片](https://user-images.githubusercontent.com/41282272/144189765-1f3b80d7-eb7e-4111-8ae8-2711c80581c5.png)

**Environment
electron15 + vue3

**Comment by vladmandic** [comment]
vue uses `webpack` and to create a bundle and it is being too smart for its own good - it tries to bundle all requirements regardless if they are for browser or node. you need to manually exclude them from `webpack` configuration  

for example, take a look at <https://github.com/vladmandic/face-api/issues/65#issuecomment-911956356>

**Comment by viis233** [comment]
thx
I found that it was environmental judgment that was wrong,**IS_BROWSER=IS_NODE=true** in electron.
I edited esm file to deal with it. have any better way ?
![图片](https://user-images.githubusercontent.com/41282272/144355337-e8edb112-c8e6-409a-a33d-da18a9793d7f.png)

**Comment by vladmandic** [comment]
`electron` creates global objects such as `process` that are normally available only in **nodejs** also available in **browsers**, so `face-api` cannot detect correctly if its running in node or browser  

i dont use **electron**, but if you create a simple git with a reproduction, i'll take a look at what i can do

**Comment by vladmandic** [comment]
i just tried `faceapi` in pure `electron` and it works just fine:

```js
import * as faceapi from './node_modules/@vladmandic/face-api/dist/face-api.esm.js';

const log = (...msg) => document.getElementById('log').innerHTML += msg + '<br>';
log(`faceapi: ${faceapi.version} browser: ${faceapi.env.isBrowser()} node: ${faceapi.env.isNodejs()}`);
log(`tfjs: ${faceapi.tf.version['tfjs-core']} browser: ${faceapi.tf.ENV.get('IS_BROWSER')} node: ${faceapi.tf.ENV.get('IS_NODE')}`);
```

    faceapi: 1.6.0 browser: true node: false
    tfjs: 3.11.0-20211201 browser: true node: false

so your issue is configuration issue specific to `electron` + `vue` + `webpack` - something in your configuration is enabling both browser and node  environment  

i'm closing this issue as its specific to this combination of frameworks and i cannot test every combination
