### ISSUE TITLE
  return process.dlopen(module, path.toNamespacedPath(filename));

### ISSUE THREAD

**Issue by Muhammad-Ehsan-Ul-Haq** [vladmandic/face-api#9]
hey! im using your package in my project for face recognition and it works fine. i copied the same project to different computer and im getting this error. 
tried all solutions available online, reinstalled node modules a number of times, tried all versions of node and tensorflow as well as your package, not sure where is the error coming from.

here is the error stack:

  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\User\Documents\digitallending_sql\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\User\Documents\digitallending_sql\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\User\Documents\digitallending_sql\functions\facedetection.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\User\Documents\digitallending_sql\controllers\applicationController.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\User\Documents\digitallending_sql\routes\applicationRouter.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)

-------------------------------------------------------------------------------------------------------------------------------------------

im using windows 10, node 12.16.2

**Comment by vladmandic** [comment]
based on the stack, i'm assuming you're trying to use `face-api` from *nodejs*, not *browser*?  
which version of `nodejs` and `tfjs-node`?  
can you post your `package.json`  
you said you've tried reinstalling `node_modules`, but did you complete remove them first?  

quick search shows that `napi-v5\tfjs_binding.node` are typically due to binary incompatibility between nodejs and tensorflow.  
you might want to try different version of nodejs (e.g. v14 if you're using v12 or vice versa).  

i had tons of issues with nodejs binary compatibilities on windows platform when i've started with node a year ago up to a point where i just gave up and ended up using **WSL2** on Windows 10 as my dev platform - works like a charm. did you consider that?

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
**--yes im using from node.js** 

**--this is my package.json file**

{
	"name": "node",
	"version": "0.0.0",
	"private": true,
	"scripts": {
		"start": "node ./bin/www"
	},
	"dependencies": {
		"@tensorflow/tfjs-node": "2.6.0",
		"@vladmandic/face-api": "0.8.3",
		"axios": "^0.20.0",
		"canvas": "^2.6.1",
		"cmake-js": "^6.1.0",
		"cookie-parser": "~1.4.4",
		"cors": "^2.8.5",
		"cron": "^1.8.2",
		"debug": "~2.6.9",
		"dotenv": "^8.2.0",
		"ejs": "~2.6.1",
		"express": "^4.17.1",
		"express-handlebars": "^5.2.0",
		"fcm-node": "^1.5.2",
		"fs": "0.0.1-security",
		"geo-distance": "^0.2.0",
		"handlebars": "^4.7.6",
		"http-errors": "^1.8.0",
		"image-js": "^0.21.9",
		"images-to-pdf": "^1.0.3",
		"jsonwebtoken": "^8.5.1",
		"morgan": "~1.9.1",
		"multer": "^1.4.2",
		"mysql": "^2.18.1",
		"mz": "^2.7.0",
		"nexmo": "^2.9.1",
		"node-cron": "^2.0.3",
		"node-fetch": "^2.6.1",
		"node-geocoder": "^3.27.0",
		"node-gyp": "^7.1.2",
		"nodemailer": "^6.4.14",
		"nodemon": "^2.0.6",
		"password-hash": "^1.2.2",
		"path": "^0.12.7",
		"puppeteer": "^5.4.0"
	},
	"devDependencies": {
		"decache": "^4.6.0"
	}
}

**--yes i deleted node_modules every time i installed again.
-- this is the whole log after npm install**

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\User\Documents\digitallending_sql> npm i

> hummus@1.0.108 install C:\Users\User\Documents\digitallending_sql\node_modules\hummus
> node-pre-gyp install --fallback-to-build $EXTRA_NODE_PRE_GYP_FLAGS

node-pre-gyp WARN Using request for node-pre-gyp https download
[hummus] Success: "C:\Users\User\Documents\digitallending_sql\node_modules\hummus\binding\hummus.node" is installed via remote

> grpc@1.24.3 install C:\Users\User\Documents\digitallending_sql\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "C:\Users\User\Documents\digitallending_sql\node_modules\grpc\src\node\extension_binary\node-v72-win32-x64-unknown\grpc_node.node" is installed via remote

> @tensorflow/tfjs-node@2.7.0 install C:\Users\User\Documents\digitallending_sql\node_modules\@tensorflow\tfjs-node
> node scripts/install.js

CPU-windows-2.7.0.zip
* Downloading libtensorflow
[==============================] 984174/bps 100% 0.0s
* Building TensorFlow Node.js bindings

> canvas@2.6.1 install C:\Users\User\Documents\digitallending_sql\node_modules\canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[canvas] Success: "C:\Users\User\Documents\digitallending_sql\node_modules\canvas\build\Release\canvas.node" is installed via remote

> puppeteer@5.4.0 install C:\Users\User\Documents\digitallending_sql\node_modules\puppeteer
> node install.js

Downloading Chromium r809590 - 153.5 Mb [====================] 100% 0.0s
Chromium (809590) downloaded to C:\Users\User\Documents\digitallending_sql\node_modules\puppeteer\.local-chromium\win64-809590

> core-js@3.6.5 postinstall C:\Users\User\Documents\digitallending_sql\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> protobufjs@6.9.0 postinstall C:\Users\User\Documents\digitallending_sql\node_modules\protobufjs
> node scripts/postinstall


> node-cron@2.0.3 postinstall C:\Users\User\Documents\digitallending_sql\node_modules\node-cron
> opencollective-postinstall

Thank you for using node-cron!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/node-cron/donate


> nodemon@2.0.6 postinstall C:\Users\User\Documents\digitallending_sql\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 727 packages from 470 contributors and audited 730 packages in 719.394s

35 packages are looking for funding
  run `npm fund` for details

found 4 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details


**--- typing npn audit shows the following**

 === npm audit security report ===                        
                                                                                
                                                                                
                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           
                                                                                
                                                                                
  High            Prototype Pollution in node-forge                             
                                                                                
  Package         node-forge                                                    
                                                                                
  Patched in      >= 0.10.0                                                     
                                                                                
  Dependency of   fcm-node                                                      
                                                                                
  Path            fcm-node > firebase-admin > @google-cloud/firestore >         
                  google-gax > google-auth-library > gtoken > google-p12-pem >  
                  node-forge                                                    
                                                                                
  More info       https://npmjs.com/advisories/1561                             
                                                                                
                                                                                
  High            Prototype Pollution in node-forge                             
                                                                                
  Package         node-forge                                                    
                                                                                
  Patched in      >= 0.10.0                                                     
                                                                                
  Dependency of   fcm-node                                                      
                                                                                
  Path            fcm-node > firebase-admin > @google-cloud/storage >           
                  @google-cloud/common > google-auth-library > gtoken >         
                  google-p12-pem > node-forge                                   
                                                                                
  More info       https://npmjs.com/advisories/1561                             
                                                                                
                                                                                
  High            Prototype Pollution in node-forge                             
                                                                                
  Package         node-forge                                                    
                                                                                
  Patched in      >= 0.10.0                                                     
                                                                                
  Dependency of   fcm-node                                                      
                                                                                
  Path            fcm-node > firebase-admin > @google-cloud/storage >           
                  gcs-resumable-upload > google-auth-library > gtoken >         
                  google-p12-pem > node-forge                                   
                                                                                
  More info       https://npmjs.com/advisories/1561                             
                                                                                
                                                                                
  High            Prototype Pollution in node-forge                             
                                                                                
  Package         node-forge                                                    
                                                                                
  Patched in      >= 0.10.0                                                     
                                                                                
  Dependency of   fcm-node                                                      
                                                                                
  Path            fcm-node > firebase-admin > node-forge                        
                                                                                
  More info       https://npmjs.com/advisories/1561                             
                                                                                
found 4 high severity vulnerabilities in 730 scanned packages
  4 vulnerabilities require manual review. See the full report for details.

**--WSL2, i havent but plan to do soon**

**Comment by vladmandic** [comment]
thanks  

since you have `@tensorflow/tfjs-node": "2.6.0` as a direct dependency in your project,  
did you try using face-api **nobundle** version (see docs on how to use it)?  
so it's not using bundled `tfjs` and instead relying on whatever you have installed yourself?

e.g., if you're using `require`
```js
const faceapi = require('../dist/face-api.nobundle.js');
```
or if you're using `import`
```js
import * as faceapi from '../dist/face-api.nobundle.js';
```

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
i have tried previous versions as well but no luck

im not sure about nobundle version of faceapi

**Comment by vladmandic** [comment]
@Muhammad-Ehsan-Ul-Haq I just posted how to use nobundle version

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
it says for client side, im trying to use it on server-side nodejs

**Comment by vladmandic** [comment]
i just updated build in versiom 0.8.5 (published now) to produce different versions:
- `dist/face-api.js`: IIFE format for client-side Browser execution
- `dist/face-api.esm.js`: ESM format for client-side Browser execution with TFJS pre-bundled
- `dist/face-api.esm.nobundle.js`: ESM format for client-side Browser execution without TFJS and not minified
- `dist/face-api.node.js`: CommonJS format for server-side NodeJS execution with TFJS pre-bundled
- `dist/face-api.node.nobundle.js`: CommonJS format for server-side NodeJS execution without TFJS and not minified

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
internal/modules/cjs/loader.js:1206
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\LoanApp-master\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node


same error

**Comment by vladmandic** [comment]
That almost rules out `face-api` as it's not loading `tfjs-node` anymore.

Any chance you can setup a simple project on that system just importing and initializing `tfjs-node` without any other dependencies to rule out things?

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
im really new to this and might not be able to do the task done.
can you create a simple project for me ?

**Comment by vladmandic** [comment]
this should be enough  
<https://gist.github.com/vladmandic/4c128a688ed3addd82a3eb5d96fbc2f3>

**Comment by vladmandic** [comment]
@Muhammad-Ehsan-Ul-Haq any updates?

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
sorry took a while to respond, i was reinstalling windows on this pc and all softwares to see if they were the problem and still i am facing the same issue.
with the code you provided, i still have the same error. let me paste it here below.



PS C:\Users\Hamza's PC\Documents\test> node test.js
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\dist\index.js:49
    throw new Error("The Node.js native addon module (tfjs_binding.node) can not " +
    ^

Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node.
Please run command 'npm rebuild @tensorflow/tfjs-node build-addon-from-source' to rebuild the native addon module.
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\dist\index.js:49:11)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Hamza's PC\Documents\test\test.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)

**Comment by vladmandic** [comment]
ok, so this rules out that issue is not in `face-api` as it happens without it  

the issue is that `nodejs` cannot load tensorflow binary binding
- possibly a path issue: i've noticed that there is `'` in `Hamza's` which may confuse nodejs
  can you create a new user on that system with a simple user name so path does not contain extended characters?
- possibly missing file due to bad `@tensorflow/tfjs-node` installation
  check if file `C:\Users\Hamza's PC\Documents\test\node_modules@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node.` exists.
- possibly an incompatibility between specific binary versions of `nodejs` and `@tensorflow/tfjs-node`
   try rebuilding bindings manually by running `npm run build-addon-from-source` inside `C:\Users\Hamza's PC\Documents\test\node_modules@tensorflow\tfjs-node`

if none of those work, check for matching open issues on `tfjs` board: <https://github.com/tensorflow/tfjs/issues?q=tfjs_binding.node>

and report a new issue there.

i can keep this issue open a bit longer, but there is really not much i can do here since issue is strictly between `nodejs` and `tensorflow` binary bindings.

once again, i really advocate for WSL2 on Windows 10 - it avoids all of binary issues on Windows 10 platform since for all intended purposes it's linux.

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
C:\Users\Hamza's PC\Documents\test\node_modules@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node.
**does not exist** 
i checked it and the file was not there

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
only file that exists in the vapi-v5 folder is tensorflow.dll

**Comment by vladmandic** [comment]
can you search for `tfjs_binding.node` if it's somewhere else on you PC and place it in that folder?
seems like `@tensorflow/tfjs-node` installation is what goes wrong.

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
after this 

possibly an incompatibility between specific binary versions of nodejs and @tensorflow/tfjs-node
try rebuilding bindings manually by running npm run build-addon-from-source inside C:\Users\Hamza's PC\Documents\test\node_modules@tensorflow\tfjs-node


i got this error 

npm run build-addon-from-source -m
       
> @tensorflow/tfjs-node@2.7.0 build-addon-from-source C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node    
> node-pre-gyp install --build-from-source

node-pre-gyp WARN Using needle for node-pre-gyp https download 
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(440,26): er
ror MSB4100: Expected "$([System.String]::new('%(Link.AdditionalDependencies)').Contains('atls.lib'))" to evaluate to a boolea
n instead of "$([System.String]::new('kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole 
32.lib;oleaut32.lib;uuid.lib;odbc32.lib;DelayImp.lib;"C:\\Users\\Hamza's PC\\AppData\\Local\\node-gyp\\Cache\\12.16.2\\x64\\no 
de.lib";tensorflow.lib;Delayimp.lib').Contains('atls.lib'))", in condition "'$(ATL_KeyFile)' != '' and ('$(ConfigurationType)' 
 == 'Application' or '$(ConfigurationType)' == 'DynamicLibrary') [C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\
tfjs-node\build\tfjs_binding.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(440,26): er 
ror MSB4100:                          and %(Link.AdditionalDependencies) != '' and  $([System.String]::new('%(Link.AdditionalD 
ependencies)').Contains('atls.lib'))". [C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\build\tfjs_bindi 
ng.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23) 
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--build-from-source" "--module=C:\\Users\\Hamza's PC\\Documents\\test\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v5\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\Users\\Hamza's PC\\Documents\\test\\node_modules\\@tensorflow\\tfjs-node\\lib\\napi-v5" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=5" "--node_napi_label=napi-v5"
gyp ERR! cwd C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --build-from-source --module=C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\lib\napi-v5 --napi_version=5 --node_abi_napi=napi --napi_build_version=5 --node_napi_label=napi-v5' 
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Hamza's PC\Documents\test\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hamza's PC\\Documents\\test\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--build-from-source"
node-pre-gyp ERR! cwd C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node
node-pre-gyp ERR! node -v v12.16.2
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --build-from-source --module=C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node\lib\napi-v5 --napi_version=5 --node_abi_napi=napi --napi_build_version=5 --node_napi_label=napi-v5' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tensorflow/tfjs-node@2.7.0 build-addon-from-source: `node-pre-gyp install --build-from-source`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tensorflow/tfjs-node@2.7.0 build-addon-from-source script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hamza's PC\AppData\Roaming\npm-cache\_logs\2020-10-30T20_02_33_528Z-debug.log
PS C:\Users\Hamza's PC\Documents\test\node_modules\@tensorflow\tfjs-node>

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
i searched for the file and found nothing anywhere

**Comment by vladmandic** [comment]
that file is a "map" of `tensorflow.dll` functions so `nodejs` can use it.  
it's supposed to be created during installation, but in your cases it's missing and you can't generate it yourself.  

last thing to try is to run from a different user to avoid suspect `'` character in path.

this is definitely a bug in `@tensorflow/tfjs-node` installation - can you open an issue there?

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
i have gtx1050 graphics card installed on my system and i believe that might be the issue somehow as everything is working fine on my other system. have any idea about that?

**Comment by vladmandic** [comment]
no, as `tfjs-node` does not look at GPU, it uses software implementation in `tensorflow.dll`.  
if you used `tfjs-node-gpu`, that would be a GPU-accelerated version (and it requires nVidia CUDA toolkit to work).  
(if there were problems and you used `tfjs-node-gpu`, first thing i'd ask you to try `tfjs-node` package.)

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
oh okay, thanks a lot for all the support!

**Comment by vladmandic** [comment]
you can try to copy the missing file from your other system.

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
yes, let me try

**Comment by Muhammad-Ehsan-Ul-Haq** [comment]
if a copy a running project on this system i get this error.


[nodemon] starting `node ./bin/www start`
node-pre-gyp info This Node instance does not support builds for N-API version 6
node-pre-gyp info This Node instance does not support builds for N-API version 6
internal/modules/cjs/loader.js:1206
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Hamza's PC\Documents\digitallending_sql\node_modules\@tensorflow\tfjs-node\lib\napi-v5\tfjs_binding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Hamza's PC\Documents\digitallending_sql\node_modules\@tensorflow\tfjs-node\dist\index.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Hamza's PC\Documents\digitallending_sql\functions\facedetection.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Hamza's PC\Documents\digitallending_sql\controllers\applicationController.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Hamza's PC\Documents\digitallending_sql\routes\applicationRouter.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)

**Comment by vladmandic** [comment]
i thought that might happen, if systems are not identical the `tfjs_binding.node` will not match - like i said earlier, it's normally built during installation of `tfjs-node`.

open a new issue at <https://github.com/tensorflow/tfjs/issues> and copy important parts of this thread.

**Comment by vladmandic** [comment]
closing the issue as the root cause is bug in `@tensorflow/tfjs-node` installer for Windows platform - issue should be tracked in `tfjs`.
