### ISSUE TITLE
add support for react-native with expo

### ISSUE THREAD

**Issue by toguvr** [vladmandic/face-api#90]
**Issue Description**
When i use the same i used in reactjs on react native it says this: "[Unhandled promise rejection: Error: getEnv - environment is not defined, check isNodejs() and isBrowser()]"

**Steps to Reproduce**

Do on react native project this lines:
where user.avatar_url can be any other face image
async function onSelectionChangedFirst() {
    // await faceapi.loadFaceRecognitionModel(MODEL_URL);
    await faceapi.nets.ssdMobilenetv1.loadFromUri(MODEL_URL);
    // if (!isFaceDetectionModelLoaded()) {
    //   return;
    // }
    if (!user?.avatar_url) {
      return;
    }

    const options = getFaceDetectorOptions();

    const input1 = await faceapi.fetchImage(user.avatar_url);

    const detections1 = await faceapi.detectAllFaces(input1, options);

    const faceImages1 = await faceapi.extractFaces(input1, detections1);

    if (faceImages1.length > 0) {
      setPreview1(faceImages1[0].toDataURL());

      const fim1 = await faceapi.computeFaceDescriptor(faceImages1[0]);

      setDescriptor1(fim1);
    } else {
      Alert.alert("sem nenhum rosto na foto");
    }
  }

**Expected Behavior**

**Environment
react native
- Module version?
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? js
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? react native
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)?
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
`react-native` is not supported as `face-api` internally relies on DOM elements  

it is a valid enhacement request, but i doubt i would prioritize it at the moment since `face-api` is in maintenance mode  

however, contributions are welcome

**Comment by toguvr** [comment]
Do you know how can I Beegin at this? Because I can't load the weights and without this, I can't do nothing

**Comment by toguvr** [comment]
Do you know how can I Beegin at this? Because I can't load the weights and without this, I can't do nothing

**Comment by vladmandic** [comment]
- clone `face-api` and install dev dependencies so you can change the sources
- modify `src/env/isBrowser.ts` to return `true` so `face-api` gets initialized as in normal browser environment
- run `npm build` to rebuild `face-api`
- see what else needs to get modified

**Comment by vladmandic** [comment]
closing as will not implement, but if the PR is submitted it will be reviewed and possibly included.
