### ISSUE TITLE
Provide build for WASM on node

### ISSUE THREAD

**Issue by marcelklehr** [vladmandic/face-api#93]
**Issue Description**

I would like to run face-api using tensorflow in WASM.

**Steps to Reproduce**

When loading face-api, it automatically requires tfjs-node, which loads libtensorflow, which is not compatible with my architecture.

**Expected Behavior**

I'd like to have a node.js build that requires tfjs, so I can setBackend(wasm)

**Environment

- Module version? 1.5
- Built-in demo or custom code? custom
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? js
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Node.js 14.x
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Ubuntu Linux
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)? -

**Comment by vladmandic** [comment]
ive added `nodejs` with `wasm` target, library is in `dist/face-api.node-wasm.js`

it expects that '@tensorflow/tfjs' and '@tensorflow/tfjs-backend-wasm' are manually imported before `faceapi`

```js
Compile: { name: 'faceapi/node/wasm', format: 'cjs', platform: 'node', input: 'src/index.ts', output: 'dist/face-api.node-wasm.js', files: 162, inputBytes: 234871, outputBytes: 174962 }
```

**Comment by marcelklehr** [comment]
Thank you so much :)
