### ISSUE TITLE
Detecting additional face deformation attributes

### ISSUE THREAD

**Issue by maddygoround** [vladmandic/face-api#94]
Hi,

Is it possible to detect attributes like acne, moles and wrinkles on face inside this library? if not then can you suggest a way to extend this library to support above parameters?

**Comment by vladmandic** [comment]
no, this library cannot detect such features and its currently not planned to expand it in that direction.  

if you had a trained models for such items, you could use `faceapi` to detect faces and crop them before passing them on for further processing, but that's about it.
