### ISSUE TITLE
Resource load failed

### ISSUE THREAD

**Issue by busyShadow** [vladmandic/face-api#96]
**Issue Description**
Vue2 builds a demo, loadFromUri loads tinyFaceDetector, and loads loadFaceLandmarkModel, PC loads resources successfully, but Apple mobile safari fails to load

**Expected Behavior**
Resources can be loaded on both PC and mobile

**Environment
window 10 + chrome 98.0.4758.102(PC) + safari(mobile)

- Module version?
"@vladmandic/face-api": "^1.6.5"
"vue": "^2.5.2"

- Built-in demo or custom code?
https://busyshadow.github.io/#/

- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
js

- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?
webpack

- For installation or startup issues include your `package.json`
```
{
  "name": "faceDemo",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "",
  "private": true,
  "scripts": {
    "dev": "vue-cli-service serve",
    "build": "vue-cli-service build"
  },
  "dependencies": {
    "@vladmandic/face-api": "^1.6.5",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "vconsole": "^3.12.0",
    "vue": "^2.5.2",
    "vue-router": "^3.1.6"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.3.1",
    "@vue/cli-plugin-router": "~4.3.1",
    "@vue/cli-service": "~4.3.1",
    "vue-template-compiler": "^2.6.11"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```
#### index.vue
```
<template>
    <div>
        <div>err1:{{err1}}</div>
        <div>err2:{{err2}}</div>
    </div>
</template>
<script>
    import * as faceapi from '@vladmandic/face-api';
    // import * as faceapi from "face-api.js";
    import vconsole from 'vconsole';
    let _this;
    export default {
        data(){
            return {
                err1:"",
                err2:"",
            }
        },
        created(){
            new vconsole();
        },
        mounted(){
            _this = this;
            this.$nextTick(() => {
                this.fnInit();
            });
        },
        methods:{
            async fnInit(){
                try {
                    await faceapi.nets['tinyFaceDetector'].loadFromUri("https://busyshadow.github.io/models");
                }catch(e){
                    this.err1 = e;
                }
                try {
                    await faceapi.loadFaceLandmarkModel("https://busyshadow.github.io/models");
                } catch(e){
                    this.err2 = e;
                }

                _this.options = new faceapi.TinyFaceDetectorOptions({
                    inputSize: 224, // 160 224 320 416 512 608
                    scoreThreshold: 0.3, // 0.1 ~ 0.9
                });
            }
        }
    }
</script>
```
success
![success](https://user-images.githubusercontent.com/20067728/155680194-084dad0a-a9ec-4865-be49-486e4b46ccba.png)

error
![error](https://user-images.githubusercontent.com/20067728/155680448-21f0ef2b-3540-4997-8e14-272a8f622f77.jpg)

**Comment by vladmandic** [comment]
line 

> faceapi.nets['tinyFaceDetector'].loadFromUri("https://busyshadow.github.io/models");

gets interpreted as load from `uri` + `model_name` + `-weights_manifest.json`

and in your case, url of the actual fetch request ends up as having `unknown` as model name,  
so it fails loading with **404** not found error  

but model name is a static property of each model, so only way it could be unknown if class never got instantiated to start with - something went terribly wrong before actual loading  

to confirm, can you add this check before load call?

> console.log(faceapi.nets.tinyFaceDetector.getDefaultModelName());

it should report `tiny_face_detector_model`

and is there anything else reported in the browser inspector before this error?

**Comment by busyShadow** [comment]
> is there anything else reported in the browser inspector before this error?

There is no other error output until the error occurs.

I changed the compressed js and css resource configuration in vue.config.js, and now no errors are reported. I reported an error before, I put the compiled js files in the static folder【eg: static/js/xxx.js】. Now the configuration of vue.config.js
```
module.exports = {
    publicPath: './',
    assetsDir: 'static',
    productionSourceMap: false,
    lintOnSave: process.env.NODE_ENV !== 'production',
    devServer: {
        historyApiFallback: false,
        noInfo: false,
        host: "localhost",
        hot: true,
        inline: true,
        watchOptions: {
            ignored: ['node_modules'],
            aggregateTimeout: 600
        },
        overlay: {
            errors: true,
            warnings: false
        },
    },
    css: {
    },
    configureWebpack: config => {
        config.resolve.alias['vue$'] = 'vue/dist/vue.esm.js';
        return {
            output: {
                filename: `[name].[contentHash].js`,
                chunkFilename: `[name].[contentHash].js`
            }
        };
    },
    chainWebpack: config => {
        config.plugins.delete('prefetch');
    }
};

```
>console.log(faceapi.nets.tinyFaceDetector.getDefaultModelName());
now, yes

![1645797578(1)](https://user-images.githubusercontent.com/20067728/155727756-eafae9fb-ef18-4d2b-8745-aabd73732967.png)
There is an error, I don't know if it has any effect

**Comment by busyShadow** [comment]
Next Monday, I will go back to the company to see how the configuration in question is written

**Comment by vladmandic** [comment]
so loading error is gone?

regarding webgl, safari on mobile does not support webgl version 2, only obsolete version 1 - which i find incredible by apple, but nothing i can do about it. `faceapi` will try webgl2 first, but if it cannot get it, it should work with `webgl1` as well - with focus on *should* since i don't have a way of testing it (nor i want to go back putting too much effort into something that is obsolete).

**Comment by busyShadow** [comment]
hi, I reproduced
I try to output 
>console.log(faceapi.nets.tinyFaceDetector.getDefaultModelName());

It does output tiny_face_detector_model, but it still fails to load

[my test source address](https://github.com/busyShadow/busyShadow.github.io/tree/master/source)

**Comment by busyShadow** [comment]
I try to switch to face-api.js, it works fine under the same configuration

**Comment by busyShadow** [comment]
There is no error in my android
![image](https://user-images.githubusercontent.com/20067728/155989542-0fcbe7cd-893f-491b-a1b3-06abc598c353.png)
safari
![image](https://user-images.githubusercontent.com/20067728/155989568-77957a87-34dc-41c5-88c4-4650cdc9e2d3.png)

**Comment by vladmandic** [comment]
> I try to switch to face-api.js, it works fine under the same configuration

> local preview with https://localhost:8080, safari and android are working fine. Only after packaging safari has an exception.

IMO, those two statements are significant:
- original `face-api.js` is packaged as obsolete `umd` package,  
  so when `vue` asks `webpack` to create a package, there it just takes `face-api` as-is as it cant do anything else with it  
- my version of `face-api` is packaged as `esm` package  
  and it seems that `vue` configuration for `webpack` is ok for **dev** mode,  
  but its not ok for **prod** mode and `webpack` does something bad.

unfortunately, i don't know anything how vue -> webpack configuration works.

but alternatively, why not do a dynamic import of `face-api` - i don't like when vue/angular/react/whatever try to repackage everything anyhow.

**Comment by busyShadow** [comment]
ok。I made some attempts, `vue.config.js`custom output, safari and android work fine, but I don't know what effect this way will bring, only for reference.
![1646061537(1)](https://user-images.githubusercontent.com/20067728/156008601-58264906-3e55-455d-b366-8075a5258247.png)
![a683080adf356fc4ab442c24dc5722c](https://user-images.githubusercontent.com/20067728/156009348-1d551080-1e9d-43e1-ae68-0f292294ec3a.jpg)

**Comment by vladmandic** [comment]
interesting, i didn't expect that kind of a change to do much - it basically removes hash from filename and thats it, i'd expect only side-effect might be less aggressive browser cache invalidation

**Comment by busyShadow** [comment]
Will not be compiled by webpack, there is a way to introduce it in the [browser](https://github.com/vladmandic/face-api#1-iife-script). Introduce `face-api` under` pubilc/index.html`
It works fine under android and safari
If anyone else has a better way, welcome to add

**Comment by vladmandic** [comment]
i'm not sure is there an ask in the last message?

**Comment by vladmandic** [comment]
closing
